<?php

namespace ccxt\async;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\async\abstract\kalshi as Exchange;
use \React\Async;
use \React\Promise;
use \React\Promise\PromiseInterface;

class kalshi extends Exchange {

    public function describe() {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'kalshi',
            'name' => 'Kalshi',
            'countries' => array( 'US' ),
            'rateLimit' => 100,
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'cancelAllOrders' => true,
                'cancelOrder' => true,
                'createOrder' => true,
                'fetchBalance' => true,
                'fetchCurrencies' => false,
                'fetchEvents' => true,
                'fetchMarkets' => true,
                'fetchOHLCV' => true,
                'fetchOpenOrders' => true,
                'fetchOrder' => true,
                'fetchOrderBook' => true,
                'fetchPositions' => true,
                'fetchTicker' => true,
                'fetchTickers' => false,
                'fetchTrades' => true,
                'prediction' => true,
            ),
            'timeframes' => array(
                '1m' => 1,
                '5m' => 5,
                '15m' => 15,
                '1h' => 60,
                '6h' => 360,
                '1d' => 1440,
            ),
            'urls' => array(
                'logo' => 'https://kalshi.com/favicon.ico',
                'api' => array(
                    'kalshi' => 'https://api.elections.kalshi.com/trade-api/v2',
                ),
                'test' => array(
                    'kalshi' => 'https://demo-api.kalshi.co/trade-api/v2',
                ),
                'www' => 'https://kalshi.com',
                'doc' => array( 'https://trading-api.readme.io/reference/getting-started' ),
            ),
            'api' => array(
                'kalshi' => array(
                    'public' => array(
                        'get' => array(
                            'events' => 1,
                            'events/{event_ticker}' => 1,
                            'series' => 1,
                            'series/{series_ticker}' => 1,
                            'markets' => 1,
                            'markets/{ticker}' => 1,
                            'markets/{ticker}/orderbook' => 1,
                            'markets/{ticker}/trades' => 1,
                            'series/{series_ticker}/markets/{ticker}/candlesticks' => 1,
                        ),
                    ),
                    'private' => array(
                        'get' => array(
                            'portfolio/balance' => 1,
                            'portfolio/orders' => 1,
                            'portfolio/orders/{order_id}' => 1,
                            'portfolio/positions' => 1,
                            'portfolio/fills' => 1,
                        ),
                        'post' => array(
                            'portfolio/orders' => 1,
                        ),
                        'delete' => array(
                            'portfolio/orders/{order_id}' => 1,
                            'portfolio/orders' => 1,
                        ),
                    ),
                ),
            ),
            'requiredCredentials' => array(
                'apiKey' => true,   // KALSHI-ACCESS-KEY (UUID)
                'privateKey' => true,   // RSA PEM private key for signing
            ),
            'fees' => array(
                'trading' => array(
                    'tierBased' => false,
                    'percentage' => true,
                    'maker' => 0.0,
                    'taker' => 0.07,  // 7% fee on profit
                ),
            ),
            'options' => array(
                'defaultFetchEventsLimit' => 100,
                'maxFetchMarketsLimit' => 1000,
                'defaultEventStatus' => 'open',  // 'open' | 'closed' | 'settled'
            ),
        ));
    }

    public function fetch_markets(array $params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            /**
             * Fetches all Kalshi markets via $cursor pagination and maps each binary market to YES and NO CCXT markets.
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/getmarkets
             *
             */
            $queries = $this->safe_list($params, 'queries', array());
            $rest = $this->omit($params, array( 'queries' ));
            $lowerQueries => stringarray() = array();
            for ($qi = 0; $qi < count($queries); $qi++) {
                $lowerQueries[] strtolower(= ($queries[$qi]));
            }
            $flatMarkets => Marketarray() = array();
            $eventsDict = array();
            $cursor = null;
            $limit = $this->safe_integer($this->options, 'maxFetchMarketsLimit', 1000);
            while (true) {
                $request = array( 'limit' => $limit );
                if ($cursor !== null) {
                    $request['cursor'] = $cursor;
                }
                $response = Async\await($this->kalshiPublicGetMarkets ($this->extend($request, $rest)));
                $rawMarkets = $this->safe_list($response, 'markets', array());
                for ($raw of $rawMarkets) {
                    if (strlen($lowerQueries) > 0) {
                        $ticker strtolower(= ($this->safe_string($raw, 'ticker') || ''));
                        $title strtolower(= ($this->safe_string($raw, 'title') || ''));
                        $matches = false;
                        for ($mi = 0; $mi < count($lowerQueries); $mi++) {
                            if (mb_strpos($ticker, $lowerQueries[$mi]) !== -1 || mb_strpos($title, $lowerQueries[$mi]) !== -1) {
                                $matches = true;
                                break;
                            }
                        }
                        if (!$matches) {
                            continue;
                        }
                    }
                    $parsed = $this->parseBinaryMarketToOutcomes ($raw);
                    $eventTicker = $this->safe_string($raw, 'event_ticker');
                    $eventTitle = $this->safe_string($raw, 'title', $eventTicker);
                    $eventKey = $eventTitle ? $this->shorten_slug($eventTitle) : null;
                    for ($m of $parsed) {
                        $flatMarkets[] = $m;
                        if ($eventKey) {
                            if (!$eventsDict[$eventKey]) {
                                $eventsDict[$eventKey] = array(
                                    'id' => $eventTicker,
                                    'slug' => $eventTicker,
                                    'symbol' => $eventKey,
                                    'title' => $eventTitle,
                                    'markets' => array(),
                                );
                            }
                            ($eventsDict[$eventKey])['markets'][] = $m;
                        }
                    }
                }
                $cursor = $this->safe_string($response, 'cursor');
                if (!$cursor || strlen($rawMarkets) < $limit) {
                    break;
                }
            }
            $this->events = $eventsDict;
            return $flatMarkets;
        }) ();
    }

    public function parse_market(array $raw): array {
        // {
        //    "can_close_early":true,
        //    "close_time":"2029-07-01T14:00:00Z",
        //    "created_time":"0001-01-01T00:00:00Z",
        //    "early_close_condition":"This market will close and expire early if the event occurs.",
        //    "event_ticker":"KXBALANCE-29",
        //    "expected_expiration_time":"2029-07-01T14:00:00Z",
        //    "expiration_time":"2029-07-01T14:00:00Z",
        //    "expiration_value":"",
        //    "fractional_trading_enabled":false,
        //    "last_price_dollars":"0.1100",
        //    "latest_expiration_time":"2029-07-01T14:00:00Z",
        //    "liquidity_dollars":"0.0000",
        //    "market_type":"binary",
        //    "no_ask_dollars":"0.9000",
        //    "no_bid_dollars":"0.8900",
        //    "no_sub_title":"During Trump's term",
        //    "notional_value_dollars":"1.0000",
        //    "open_interest_fp":"16353.00",
        //    "open_time":"2025-01-03T15:00:00Z",
        //    "previous_price_dollars":"0.0000",
        //    "previous_yes_ask_dollars":"0.0000",
        //    "previous_yes_bid_dollars":"0.0000",
        //    "price_level_structure":"linear_cent",
        //    "price_ranges":array(
        //        {
        //            "end":"1.0000",
        //            "start":"0.0000",
        //            "step":"0.0100"
        //        }
        //    ),
        //    "response_price_units":"usd_cent",
        //    "result":"",
        //    "rules_primary":"If there is not a budget deficit for any of fiscal years 2025, 2026, 2027, or 2028, then the market resolves to Yes.",
        //    "rules_secondary":"",
        //    "settlement_timer_seconds":"1800",
        //    "status":"active",
        //    "subtitle":"",
        //    "tick_size":"1",
        //    "ticker":"KXBALANCE-29",
        //    "title":"Will Trump balance the budget?",
        //    "updated_time":"0001-01-01T00:00:00Z",
        //    "volume_24h_fp":"85.00",
        //    "volume_fp":"40208.00",
        //    "yes_ask_dollars":"0.1100",
        //    "yes_ask_size_fp":"",
        //    "yes_bid_dollars":"0.1000",
        //    "yes_bid_size_fp":"",
        //    "yes_sub_title":"During Trump's term"
        // }
        $ticker = $this->safe_string($raw, 'ticker');
        $eventTicker = $this->safe_string($raw, 'event_ticker');
        $subtitle = $this->safe_string($raw, 'subtitle', $this->safe_string($raw, 'title'));
        $active = $this->safe_string($raw, 'status') === 'open';
        $endDate = $this->safe_string($raw, 'expiration_time');
        $volume = $this->safe_number($raw, 'volume');
        $liquidity = $this->safe_number($raw, 'liquidity');
        $openInt = $this->safe_number($raw, 'open_interest');
        // Derive series $ticker => drop last hyphen-segment from event_ticker
        $eventParts = $eventTicker ? explode('-', $eventTicker) : array();
        $seriesTicker = strlen($eventParts) > 1 ? mb_substr($eventParts, 0, -1 - implode('-', 0)) : $eventTicker;
        // Market symbol (no outcome suffix)
        $marketSymbol = $this->slug_to_market_symbol($eventTicker, $subtitle || $ticker);
        // Build $outcomes
        $outcomeLabels = array( 'YES', 'NO' );
        $outcomeIds = array( $ticker, $ticker . '-NO' );
        $outcomes => anyarray() = array();
        for ($oi = 0; $oi < count($outcomeLabels); $oi++) {
            $label = $outcomeLabels[$oi];
            $outcomes[] = array(
                'id' => $outcomeIds[$oi],
                'symbol' => $marketSymbol . ':' . $label,
                'marketSymbol' => $marketSymbol,
                'label' => $label,
                'active' => $active,
                'info' => array(
                    'ticker' => $ticker,
                    'eventTicker' => $eventTicker,
                    'seriesTicker' => $seriesTicker,
                    'subtitle' => $subtitle,
                    'outcomeLabel' => $label,
                    'volume' => $volume,
                    'liquidity' => $liquidity,
                    'openInterest' => $openInt,
                ),
            );
        }
        return array(
            'id' => $ticker,
            'symbol' => $marketSymbol,
            'base' => 'USD',
            'quote' => 'USD',
            'settle' => null,
            'baseId' => $ticker,
            'quoteId' => 'USD',
            'settleId' => null,
            'type' => 'prediction',
            'spot' => false,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'prediction' => true,
            'active' => $active,
            'contract' => false,
            'linear' => null,
            'inverse' => null,
            'contractSize' => null,
            'expiry' => $endDate ? $this->parse8601($endDate) : null,
            'expiryDatetime' => $endDate,
            'strike' => null,
            'optionType' => null,
            'taker' => 0.07,
            'maker' => 0.0,
            'percentage' => true,
            'tierBased' => false,
            'feeSide' => 'get',
            'precision' => array(
                'amount' => 1,
                'price' => 0.01,
            ),
            'limits' => array(
                'leverage' => array( 'min' => 1, 'max' => 1 ),
                'amount' => array( 'min' => 1, 'max' => null ),
                'price' => array( 'min' => 0.01, 'max' => 0.99 ),
                'cost' => array( 'min' => null, 'max' => null ),
            ),
            'outcomes' => $outcomes,
            'info' => $this->extend($raw, array(
                'ticker' => $ticker,
                'eventTicker' => $eventTicker,
                'seriesTicker' => $seriesTicker,
                'subtitle' => $subtitle,
                'volume' => $volume,
                'liquidity' => $liquidity,
                'openInterest' => $openInt,
            )),
            'created' => null,
        );
    }

    public function fetch_ticker(?string $outcome, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $params) {
            /**
             * Fetches the current market price and bid/ask for a single Kalshi $outcome->
             * @param $outcome
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/getmarket
             *
             */
            Async\await($this->load_markets());
            $outcomeObj = $this->outcome($outcome);
            $ticker = $this->safe_string($outcomeObj['info'], 'ticker');
            $response = Async\await($this->kalshiPublicGetMarketsTicker ($this->extend(array( 'ticker' => $ticker ), $params)));
            $raw = $this->safe_value($response, 'market', $response);
            return $this->parse_ticker($raw, $outcomeObj);
        }) ();
    }

    public function parse_ticker(array $raw, ?array $market = null): array {
        /**
         * Parses a $raw Kalshi $market object into a unified CCXT Ticker, converting cent prices to decimals.
         * @param $raw
         * @param $market
         */
        $isNo = $market ? ($market['label'] === 'NO' || $this->safe_string($market['info'], 'outcomeLabel') === 'NO') : false;
        $now = $this->milliseconds();
        $symbol = $this->safe_symbol(null, $market);
        // Kalshi prices are in cents (integer 0–99) → divide by 100
        $yesAsk = $this->safe_number($raw, 'yes_ask');
        $yesBid = $this->safe_number($raw, 'yes_bid');
        $last = $this->safe_number($raw, 'last_price');
        if ($isNo) {
            $bid = ($yesAsk !== null) ? (100 - $yesAsk) / 100 : null;
            $ask = ($yesBid !== null) ? (100 - $yesBid) / 100 : null;
            $close = ($last !== null) ? (100 - $last) / 100 : null;
        } else {
            $bid = ($yesBid !== null) ? $yesBid / 100 : null;
            $ask = ($yesAsk !== null) ? $yesAsk / 100 : null;
            $close = ($last !== null) ? $last / 100 : null;
        }
        return $this->safe_ticker(array(
            'symbol' => $symbol,
            'timestamp' => $now,
            'datetime' => $this->iso8601($now),
            'high' => null,
            'low' => null,
            'bid' => $bid,
            'bidVolume' => null,
            'ask' => $ask,
            'askVolume' => null,
            'vwap' => null,
            'open' => null,
            'close' => $close,
            'last' => $close,
            'previousClose' => null,
            'change' => null,
            'percentage' => null,
            'average' => ($bid !== null && $ask !== null) ? ($bid . $ask) / 2 : null,
            'baseVolume' => null,
            'quoteVolume' => $this->safe_number($raw, 'volume'),
            'info' => $raw,
        ), $market);
    }

    public function fetch_order_book(?string $outcome, ?int $limit = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $limit, $params) {
            /**
             * Fetches the order $book for a single Kalshi $outcome, converting YES-side cents to decimal prices.
             * @param $outcome
             * @param $limit
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/getmarketorderbook
             *
             */
            Async\await($this->load_markets());
            $outcomeObj = $this->outcome($outcome);
            $ticker = $this->safe_string($outcomeObj['info'], 'ticker');
            $isNo = $outcomeObj['label'] === 'NO';
            $response = Async\await($this->kalshiPublicGetMarketsTickerOrderbook ($this->extend(array(
                'ticker' => $ticker,
            ), $params)));
            $book = $this->safe_value($response, 'orderbook', $response);
            $timestamp = $this->milliseconds();
            // Kalshi uses YES-side perspective => `yes` = $bids, `no` = $asks (inverted)
            $rawYes = $this->safe_list($book, 'yes', array());
            $rawNo = $this->safe_list($book, 'no', array());
            // Convert [price_cents, size] → [price, size]
            $bids => anyarray() = array();
            $asks => anyarray() = array();
            if ($isNo) {
                // NO perspective => NO $bids come from $rawNo, NO $asks invert $rawYes
                for ($bi = 0; $bi < count($rawNo); $bi++) {
                    $priceCents = $this->safe_number($rawNo[$bi], 0);
                    $bids[] = [ $priceCents / 100, $this->safe_number($rawNo[$bi], 1) ];
                }
                for ($ai = 0; $ai < count($rawYes); $ai++) {
                    $priceCents = $this->safe_number($rawYes[$ai], 0);
                    $asks[] = [ (100 - $priceCents) / 100, $this->safe_number($rawYes[$ai], 1) ];
                }
            } else {
                // YES perspective => YES $bids from $rawYes, YES $asks invert $rawNo
                for ($bi = 0; $bi < count($rawYes); $bi++) {
                    $priceCents = $this->safe_number($rawYes[$bi], 0);
                    $bids[] = [ $priceCents / 100, $this->safe_number($rawYes[$bi], 1) ];
                }
                for ($ai = 0; $ai < count($rawNo); $ai++) {
                    $priceCents = $this->safe_number($rawNo[$ai], 0);
                    $asks[] = [ (100 - $priceCents) / 100, $this->safe_number($rawNo[$ai], 1) ];
                }
            }
            return $this->sorted_orders($outcome, $timestamp, $bids, $asks);
        }) ();
    }

    public function sorted_orders(?string $symbol, ?int $timestamp, array $bids, array $asks): array {
        /**
         * Sorts $bids descending and $asks ascending, then returns a CCXT-shaped OrderBook object.
         * @param $symbol
         * @param $timestamp
         * @param $bids
         * @param $asks
         */
        // Sort $bids descending, $asks ascending, match CCXT OrderBook shape
        $bids = $this->sort_by($bids, 0, true);
        $asks = $this->sort_by($asks, 0);
        return array(
            'symbol' => $symbol,
            'bids' => $bids,
            'asks' => $asks,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'nonce' => null,
        );
    }

    public function fetch_ohlcv(?string $outcome, $timeframe = '1m', ?int $since = null, ?int $limit = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $timeframe, $since, $limit, $params) {
            /**
             * Fetches OHLCV candlesticks for a single Kalshi $outcome from the candlesticks endpoint.
             * @param $outcome
             * @param $timeframe
             * @param $since
             * @param $limit
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/getcandlesticks
             *
             */
            Async\await($this->load_markets());
            $outcomeObj = $this->outcome($outcome);
            $ticker = $this->safe_string($outcomeObj['info'], 'ticker');
            $seriesTicker = $this->safe_string($outcomeObj['info'], 'seriesTicker', $ticker);
            $periodMin = $this->safe_integer($this->timeframes, $timeframe, 1);
            $request = array(
                'series_ticker' => $seriesTicker,
                'ticker' => $ticker,
                'period_interval' => $periodMin,
            );
            if ($since !== null) {
                $request['start_ts'] = $this->parse_to_int($since / 1000);
            }
            if ($limit !== null && $since !== null) {
                $tf = $this->parse_timeframe($timeframe);
                $end = ($since / 1000) . $limit * $tf;
                $now = $this->seconds();
                $request['end_ts'] = $end < $now ? $end : $now;
            }
            $response = Async\await($this->kalshiPublicGetSeriesSeriesTickerMarketsTickerCandlesticks (
                $this->extend($request, $params)
            ));
            $candles = $this->safe_list($response, 'candlesticks', array());
            return $this->parse_ohlcvs($candles, $outcomeObj, $timeframe, $since, $limit);
        }) ();
    }

    public function parse_ohlcv(array $ohlcv, ?array $market = null): array {
        /**
         * Parses a single Kalshi candlestick object into a CCXT OHLCV tuple, converting cent prices to decimals.
         * @param $ohlcv
         * @param $market
         */
        // Kalshi candlestick prices are in cents → divide by 100
        $ts = $this->safe_integer($ohlcv, 'end_period_ts');
        $open = $this->safe_number($ohlcv, 'open');
        $high = $this->safe_number($ohlcv, 'high');
        $low = $this->safe_number($ohlcv, 'low');
        $close = $this->safe_number($ohlcv, 'close');
        $vol = $this->safe_number($ohlcv, 'volume');
        return array(
            $ts !== null ? $ts * 1000 : null,
            $open !== null ? $open / 100 : null,
            $high !== null ? $high / 100 : null,
            $low !== null ? $low / 100 : null,
            $close !== null ? $close / 100 : null,
            $vol,
        );
    }

    public function fetch_trades(?string $outcome, ?int $since = null, ?int $limit = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $since, $limit, $params) {
            /**
             * Fetches public trade history for a single Kalshi market $ticker->
             * @param $outcome
             * @param $since
             * @param $limit
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/getmarkettrades
             *
             */
            Async\await($this->load_markets());
            $outcomeObj = $this->outcome($outcome);
            $ticker = $this->safe_string($outcomeObj['info'], 'ticker');
            $request = array( 'ticker' => $ticker );
            if ($limit !== null) {
                $request['limit'] = $limit;
            }
            $response = Async\await($this->kalshiPublicGetMarketsTickerTrades ($this->extend($request, $params)));
            $trades = $this->safe_list($response, 'trades', array());
            return $this->parse_trades($trades, $outcomeObj, $since, $limit);
        }) ();
    }

    public function parse_trade(array $trade, ?array $market = null): array {
        /**
         * Parses a raw Kalshi $trade object into a unified CCXT Trade object.
         * @param $trade
         * @param $market
         */
        $id = $this->safe_string($trade, 'trade_id');
        $ts = $this->parse8601($this->safe_string($trade, 'created_time'));
        $priceCents = $this->safe_number($trade, 'yes_price');
        $price = $priceCents !== null ? $priceCents / 100 : null;
        $amount = $this->safe_number($trade, 'count');
        $rawSide = $this->safe_string_lower($trade, 'taker_side');
        $side => string | null;
        if ($rawSide === 'yes') {
            $side = 'buy';
        } elseif ($rawSide === 'no') {
            $side = 'sell';
        }
        return $this->safe_trade(array(
            'id' => $id,
            'info' => $trade,
            'timestamp' => $ts,
            'datetime' => $this->iso8601($ts),
            'symbol' => $this->safe_symbol(null, $market),
            'order' => null,
            'type' => null,
            'side' => $side,
            'takerOrMaker' => 'taker',
            'price' => $price,
            'amount' => $amount,
            'cost' => ($price !== null && $amount !== null) ? $price * $amount : null,
            'fee' => null,
        ), $market);
    }

    public function fetch_balance(array $params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            /**
             * Fetches the authenticated user's USD portfolio balance from Kalshi.
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/getbalance
             *
             */
            $response = Async\await($this->kalshiPrivateGetPortfolioBalance ($params));
            return $this->parse_balance($response);
        }) ();
    }

    public function parse_balance(array $response): array {
        /**
         * Parses a Kalshi balance $response (cents) into a CCXT Balances object with a USD entry.
         * @param $response
         */
        // Kalshi balance in cents → divide by 100
        $result = array( 'info' => $response );
        $balanceCents = $this->safe_number($response, 'balance');
        $total = $balanceCents !== null ? $balanceCents / 100 : null;
        $result['USD'] = array( 'free' => $total, 'used' => 0, 'total' => $total );
        return $result;
    }

    public function fetch_positions(?array $outcomes, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcomes, $params) {
            /**
             * Fetches open market $positions for the authenticated Kalshi user.
             * @param $outcomes
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/getportfoliopositions
             *
             */
            $response = Async\await($this->kalshiPrivateGetPortfolioPositions ($params));
            $positions = $this->safe_list($response, 'market_positions', array());
            return $this->parse_positions($positions, $outcomes);
        }) ();
    }

    public function parse_position(array $position, ?array $market = null): array {
        /**
         * Parses a raw Kalshi portfolio $position into a unified CCXT Position object.
         * @param $position
         * @param $market
         */
        $ticker = $this->safe_string($position, 'ticker');
        $outcomeObj = $this->safe_outcome($ticker, $market);
        $yesContracts = $this->safe_number($position, 'position');  // positive = long YES
        $positionSide => string | null;
        if ($yesContracts !== null) {
            $positionSide = $yesContracts >= 0 ? 'long' : 'short';
        }
        return array(
            'id' => null,
            'symbol' => $this->safe_string($outcomeObj, 'symbol', $ticker),
            'timestamp' => null,
            'datetime' => null,
            'contracts' => $yesContracts !== null ? abs($yesContracts) : null,
            'contractSize' => 1,
            'side' => $positionSide,
            'notional' => null,
            'leverage' => 1,
            'unrealizedPnl' => null,
            'realizedPnl' => null,
            'collateral' => null,
            'entryPrice' => null,
            'markPrice' => null,
            'liquidationPrice' => null,
            'hedged' => false,
            'maintenanceMargin' => null,
            'maintenanceMarginPercentage' => null,
            'initialMargin' => null,
            'initialMarginPercentage' => null,
            'marginRatio' => null,
            'marginMode' => 'cross',
            'marginType' => 'cross',
            'percentage' => null,
            'info' => $position,
        );
    }

    public function fetch_open_orders(?string $outcome = null, ?int $since = null, ?int $limit = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $since, $limit, $params) {
            /**
             * Fetches resting (open) $orders for the authenticated Kalshi user, optionally filtered by ticker.
             * @param $outcome
             * @param $since
             * @param $limit
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/getorders
             *
             */
            $request = array( 'status' => 'resting' );
            $outcomeObj = null;
            if ($outcome !== null) {
                $outcomeObj = $this->outcome($outcome);
                $request['ticker'] = $this->safe_string($outcomeObj['info'], 'ticker');
            }
            $response = Async\await($this->kalshiPrivateGetPortfolioOrders ($this->extend($request, $params)));
            $orders = $this->safe_list($response, 'orders', array());
            return $this->parse_orders($orders, $outcomeObj, $since, $limit);
        }) ();
    }

    public function fetch_order(?string $id, ?string $symbol = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($id, $symbol, $params) {
            /**
             * Fetches a single order by ID from the Kalshi portfolio endpoint.
             * @param $id
             * @param $symbol
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/getorder
             *
             */
            $response = Async\await($this->kalshiPrivateGetPortfolioOrdersOrderId ($this->extend(array( 'order_id' => $id ), $params)));
            return $this->parse_order($this->safe_value($response, 'order', $response));
        }) ();
    }

    public function parse_order(array $order, ?array $market = null): array {
        /**
         * Parses a raw Kalshi $order object into a unified CCXT Order object.
         * @param $order
         * @param $market
         */
        $id = $this->safe_string($order, 'order_id');
        $ticker = $this->safe_string($order, 'ticker');
        $mkt = $this->safe_outcome($ticker, $market);
        $status = $this->parse_order_status($this->safe_string($order, 'status'));
        $side = $this->safe_string($order, 'action') === 'buy' ? 'buy' : 'sell';
        $priceCents = $this->safe_number($order, 'no_price', $this->safe_number($order, 'yes_price'));
        $price = $priceCents !== null ? $priceCents / 100 : null;
        $amount = $this->safe_number($order, 'count');
        $filled = $this->safe_number($order, 'filled_count', 0);
        $remaining = ($amount !== null && $filled !== null) ? $amount - $filled : null;
        $ts = $this->parse8601($this->safe_string($order, 'created_time'));
        return $this->safe_order(array(
            'id' => $id,
            'clientOrderId' => $this->safe_string($order, 'client_order_id'),
            'info' => $order,
            'timestamp' => $ts,
            'datetime' => $this->iso8601($ts),
            'lastTradeTimestamp' => null,
            'status' => $status,
            'symbol' => $mkt['symbol'],
            'type' => $this->safe_string_lower($order, 'type', 'limit'),
            'timeInForce' => 'GTC',
            'postOnly' => null,
            'side' => $side,
            'price' => $price,
            'stopPrice' => null,
            'triggerPrice' => null,
            'average' => null,
            'amount' => $amount,
            'cost' => null,
            'filled' => $filled,
            'remaining' => $remaining,
            'fee' => null,
            'trades' => array(),
        ), $mkt);
    }

    public function parse_order_status(?string $status): ?string {
        /**
         * Maps a Kalshi order $status string to the CCXT unified $status vocabulary.
         * @param $status
         */
        $statuses = array(
            'resting' => 'open',
            'executed' => 'closed',
            'canceled' => 'canceled',
            'pending' => 'open',
        );
        return $this->safe_string($statuses, $status, $status);
    }

    public function create_order(?string $outcome, ?string $type, ?string $side, ?float $amount, ?float $price = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $type, $side, $amount, $price, $params) {
            /**
             * Places a limit or market order on Kalshi for the given $outcome token.
             * @param $outcome
             * @param $type
             * @param $side
             * @param $amount
             * @param $price
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/createorder
             *
             */
            Async\await($this->load_markets());
            $outcomeObj = $this->outcome($outcome);
            $ticker = $this->safe_string($outcomeObj['info'], 'ticker');
            $outcomeLabel = $outcomeObj['label'];
            $priceCents = $price !== null ? $this->parse_to_int($price * 100 + 0.5) : null;
            $request = array(
                'action' => $side === 'buy' ? 'buy' : 'sell',
                'count' => $amount,
                'side' => $outcomeLabel === 'NO' ? 'no' : 'yes',
                'ticker' => $ticker,
                'type' => $type,
            );
            if ($priceCents !== null) {
                $request[$outcomeLabel === 'NO' ? 'no_price' : 'yes_price'] = $priceCents;
            }
            $response = Async\await($this->kalshiPrivatePostPortfolioOrders ($this->extend($request, $params)));
            return $this->parse_order($this->safe_value($response, 'order', $response), $outcomeObj);
        }) ();
    }

    public function cancel_order(?string $id, ?string $symbol = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($id, $symbol, $params) {
            /**
             * Cancels a single open order by ID on Kalshi.
             * @param $id
             * @param $symbol
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/cancelorder
             *
             */
            $response = Async\await($this->kalshiPrivateDeletePortfolioOrdersOrderId ($this->extend(array( 'order_id' => $id ), $params)));
            return $this->parse_order($this->safe_value($response, 'order', $response));
        }) ();
    }

    public function cancel_all_orders(?string $outcome = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $params) {
            /**
             * Cancels all open orders on Kalshi, optionally scoped to one $outcome ticker.
             * @param $outcome
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/cancelorders
             *
             */
            $request = array();
            if ($outcome !== null) {
                Async\await($this->load_markets());
                $outcomeObj = $this->outcome($outcome);
                $request['ticker'] = $this->safe_string($outcomeObj['info'], 'ticker');
            }
            $response = Async\await($this->kalshiPrivateDeletePortfolioOrders ($this->extend($request, $params)));
            return $this->parse_orders($this->safe_list($response, 'orders', array()));
        }) ();
    }

    public function fetch_events(array $queries = [], array $params = array ()): PromiseInterface {
        return Async\async(function () use ($queries, $params) {
            /**
             * Fetches Kalshi events via $cursor-paginated /events, filters client-side by query strings,
             * then fetches full event details with nested markets in parallel and caches in $this->events.
             * @param $queries
             * @param $params
             *
             * @see https://trading-api.readme.io/reference/getevents
             *
             */
            $status = $this->safe_string($params, 'status', $this->safe_string($this->options, 'defaultEventStatus', 'open'));
            $pageLimit = $this->safe_integer($params, 'limit', 200);
            $maxPages = $this->safe_integer($params, 'maxPages', 5);
            $rest = $this->omit($params, array( 'status', 'limit', 'maxPages' ));
            if (!$this->events) {
                $this->events = array();
            }
            if (!$this->markets) {
                $this->markets = array();
            }
            $lowerQueries => stringarray() = array();
            for ($qi = 0; $qi < count($queries); $qi++) {
                $lowerQueries[] strtolower(= ($queries[$qi]));
            }
            // Phase 1 => sequential $cursor scan (lightweight — no nested markets) to collect matching tickers
            $matchedTickers => stringarray() = array();
            $cursor => string | null = null;
            $page = 0;
            while ($page < $maxPages) {
                $request = array( 'status' => $status, 'limit' => $pageLimit );
                if ($cursor) {
                    $request['cursor'] = $cursor;
                }
                $response = Async\await($this->kalshiPublicGetEvents ($this->extend($request, $rest)));
                $rawEvents = $this->safe_list($response, 'events', array());
                $cursor = $this->safe_string($response, 'cursor');
                for ($rei = 0; $rei < count($rawEvents); $rei++) {
                    $rawEvent = $rawEvents[$rei];
                    $ticker = ($this->safe_string($rawEvent, 'event_ticker') || '');
                    $title strtolower(= ($this->safe_string($rawEvent, 'title') || ''));
                    $matches = (strlen($lowerQueries) === 0);
                    for ($li = 0; $li < count($lowerQueries); $li++) {
                        if (strtolower(mb_strpos($ticker), $lowerQueries[$li]) !== -1 || mb_strpos($title, $lowerQueries[$li]) !== -1) {
                            $matches = true;
                            break;
                        }
                    }
                    if ($matches && $ticker) {
                        $matchedTickers[] = $ticker;
                    }
                }
                $page++;
                if (!$cursor || strlen($rawEvents) < $pageLimit) {
                    break;
                }
            }
            // Phase 2 => fetch full event details (with nested markets) for all matched tickers in parallel
            $detailPromises => anyarray() = array();
            for ($ti = 0; $ti < count($matchedTickers); $ti++) {
                $detailPromises[] = $this->kalshiPublicGetEventsEventTicker (array( 'event_ticker' => $matchedTickers[$ti], 'with_nested_markets' => true ));
            }
            $detailResponses = Async\await(Promise\all($detailPromises));
            $result = array();
            for ($di = 0; $di < count($detailResponses); $di++) {
                $detail = $detailResponses[$di];
                $fullEvent = $this->safe_value($detail, 'event', $detail);
                $parsedEvent = $this->parse_event($fullEvent);
                $eventTitle = $this->safe_string($fullEvent, 'title');
                $eventKey = $eventTitle ? $this->shorten_slug($eventTitle) : null;
                if ($eventKey) {
                    ($this->events)[$eventKey] = $parsedEvent;
                    $result[$eventKey] = $parsedEvent;
                    $parsedMarkets = ($parsedEvent['markets'] || array());
                    for ($mi = 0; $mi < count($parsedMarkets); $mi++) {
                        $m = $parsedMarkets[$mi];
                        $this->markets[$m['symbol']] = $m;
                    }
                }
            }
            return is_array($result) ? array_values($result) : array();
        }) ();
    }

    public function parse_event(array $rawEvent): PredictionEvent {
        /**
         * Parses a raw Kalshi event object (with nested markets) into the unified CCXT event shape.
         * @param $rawEvent
         */
        // {
        //         "available_on_brokers" => true,
        //         "category" => "Politics",
        //         "collateral_return_type" => "",
        //         "event_ticker" => "KXBALANCE-29",
        //         "last_updated_ts" => "0001-01-01T00:00:00Z",
        //         "markets" => array(
        //             {
        //                 "can_close_early" => true,
        //                 "close_time" => "2029-07-01T14:00:00Z",
        //                 "created_time" => "0001-01-01T00:00:00Z",
        //                 "early_close_condition" => "This market will close and expire early if the event occurs.",
        //                 "event_ticker" => "KXBALANCE-29",
        //                 "expected_expiration_time" => "2029-07-01T14:00:00Z",
        //                 "expiration_time" => "2029-07-01T14:00:00Z",
        //                 "expiration_value" => "",
        //                 "fractional_trading_enabled" => false,
        //                 "last_price_dollars" => "0.1000",
        //                 "latest_expiration_time" => "2029-07-01T14:00:00Z",
        //                 "liquidity_dollars" => "0.0000",
        //                 "market_type" => "binary",
        //                 "no_ask_dollars" => "0.9000",
        //                 "no_bid_dollars" => "0.8900",
        //                 "no_sub_title" => "During Trump's term",
        //                 "notional_value_dollars" => "1.0000",
        //                 "open_interest_fp" => "16268.00",
        //                 "open_time" => "2025-01-03T15:00:00Z",
        //                 "previous_price_dollars" => "0.0000",
        //                 "previous_yes_ask_dollars" => "0.0000",
        //                 "previous_yes_bid_dollars" => "0.0000",
        //                 "price_level_structure" => "linear_cent",
        //                 "price_ranges" => array(
        //                     {
        //                         "end" => "1.0000",
        //                         "start" => "0.0000",
        //                         "step" => "0.0100"
        //                     }
        //                 ),
        //                 "response_price_units" => "usd_cent",
        //                 "result" => "",
        //                 "rules_primary" => "If there is not a budget deficit for any of fiscal years 2025, 2026, 2027, or 2028, then the market resolves to Yes.",
        //                 "rules_secondary" => "",
        //                 "settlement_timer_seconds" => "1800",
        //                 "status" => "active",
        //                 "subtitle" => "",
        //                 "tick_size" => "1",
        //                 "ticker" => "KXBALANCE-29",
        //                 "title" => "Will Trump balance the budget?",
        //                 "updated_time" => "0001-01-01T00:00:00Z",
        //                 "volume_24h_fp" => "28.00",
        //                 "volume_fp" => "40111.00",
        //                 "yes_ask_dollars" => "0.1100",
        //                 "yes_ask_size_fp" => "",
        //                 "yes_bid_dollars" => "0.1000",
        //                 "yes_bid_size_fp" => "",
        //                 "yes_sub_title" => "During Trump's term"
        //             }
        //         ),
        //         "mutually_exclusive" => false,
        //         "series_ticker" => "KXBALANCE",
        //         "strike_period" => "",
        //         "sub_title" => "During Trump's term",
        //         "title" => "Will Trump balance the budget?"
        // }
        $rawMarkets = $this->safe_list($rawEvent, 'markets', array());
        $marketsList => anyarray() = array();
        for ($rawMarket of $rawMarkets) {
            $parsed = $this->parse_market($rawMarket);
            $marketsList[] = $parsed;
        }
        $ticker = $this->safe_string($rawEvent, 'event_ticker');
        $title = $this->safe_string($rawEvent, 'title');
        return $this->extend(array(
            'id' => $ticker,
            'slug' => $ticker,
            'symbol' => $title ? $this->shorten_slug($title) : null,
            'title' => $title,
            'markets' => $marketsList,
            'url' => $this->safe_string($rawEvent, 'url'),
            'image' => $this->safe_string($rawEvent, 'image_url'),
            'created' => $this->parse8601($this->safe_string($rawEvent, 'created_date_iso')),
            'createdDatetime' => $this->safe_string($rawEvent, 'created_date_iso'),
            'end' => $this->parse8601($this->safe_string($rawEvent, 'end_date_iso')),
            'endDatetime' => $this->safe_string($rawEvent, 'end_date_iso'),
            'category' => $this->safe_string($rawEvent, 'category'),
            'lastUpdatedAt' => $this->parse8601($this->safe_string($rawEvent, 'last_updated_date_iso')),
            'lastUpdatedAtDatetime' => $this->safe_string($rawEvent, 'last_updated_date_iso'),
            'resolutionSource' => $this->safe_string($rawEvent, 'resolution_source'),
            'resolved' => $this->safe_bool($rawEvent, 'resolved'),
            'info' => $rawEvent,
        ));
    }

    public function sign(?string $path, mixed $api = 'kalshi', $method = 'GET', array $params = array (), ?array $headers = null, ?array $body = null) {
        /**
         * Builds the request URL and attaches RSA-PSS SHA-256 authentication $headers for private endpoints.
         * @param $path
         * @param $api
         * @param $method
         * @param $params
         * @param $headers
         * @param $body
         */
        $apiGroup = gettype($api) === 'string' ? $api : $api[0];
        $access = gettype($api) === 'string' ? 'public' : $api[1];
        $baseUrls = $this->urls['api'];
        $baseUrl = $this->safe_string($baseUrls, $apiGroup, $baseUrls['kalshi']);
        $url = $baseUrl . '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_paramspath);
        $querystring = $this->urlencode($query);
        if ($method === 'GET' && $querystring) {
            $url .= '?' . $querystring;
        }
        $headers = $this->extend(array(
            'Accept' => 'application/json',
            'Content-Type' => 'application/json',
        ), $headers || array());
        if ($access === 'private') {
            $this->check_required_credentials();
            $timestamp = (string) $this->milliseconds();
            // Signing $payload => {$timestamp}{METHOD}/{path_without_base}
            $pathForSigning = '/' . $path;
            $payload = $timestamp . $method . $pathForSigning;
            // RSA-PSS SHA-256 $signature with the private key PEM
            $signature = $this->rsa($payload, str_replace(/\\n/g, '\n', $this->privateKey), 'SHA256');
            $headers = $this->extend($headers, array(
                'KALSHI-ACCESS-KEY' => $this->apiKey,
                'KALSHI-ACCESS-SIGNATURE' => $signature,
                'KALSHI-ACCESS-TIMESTAMP' => $timestamp,
            ));
            if ($method !== 'GET' && $querystring) {
                $body = $query;
            }
        }
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
