<?php

namespace ccxt\async;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\async\abstract\polymarket as Exchange;
use ccxt\ArgumentsRequired;
use \React\Async;
use \React\Promise;
use \React\Promise\PromiseInterface;

class polymarket extends Exchange {

    public function describe() {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'polymarket',
            'name' => 'Polymarket',
            'countries' => array( 'US' ),
            'rateLimit' => 100,
            'certified' => false,
            'pro' => false,
            'has' => array(
                'CORS' => null,
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'cancelAllOrders' => true,
                'cancelOrder' => true,
                'createOrder' => true,
                'fetchBalance' => true,
                'fetchCurrencies' => false,
                'fetchDeposits' => false,
                'fetchEvents' => true,        // Custom => fetch Polymarket events
                'fetchLedger' => false,
                'fetchMarkets' => true,       // Each outcome token = one market
                'fetchMyTrades' => false,
                'fetchOHLCV' => true,
                'fetchOpenOrders' => true,
                'fetchOrder' => true,
                'fetchOrderBook' => true,
                'fetchPositions' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'fetchTrades' => true,
                'fetchWithdrawals' => false,
                'prediction' => true,         // Prediction market support
            ),
            'timeframes' => array(
                '1m' => '1',
                '5m' => '5',
                '1h' => '60',
                '6h' => '360',
                '1d' => '1440',
            ),
            'urls' => array(
                'logo' => 'https://polymarket.com/favicon.ico',
                'api' => array(
                    'gamma' => 'https://gamma-api.polymarket.com',
                    'clob' => 'https://clob.polymarket.com',
                    'data' => 'https://data-api.polymarket.com',
                ),
                'www' => 'https://polymarket.com',
                'doc' => array( 'https://docs.polymarket.com' ),
                'fees' => 'https://docs.polymarket.com/#fees',
            ),
            'api' => array(
                'gamma' => array(
                    'public' => array(
                        'get' => array(
                            'events' => 1,
                            'events/{id}' => 1,
                            'events/slug/{slug}' => 1,
                            'markets' => 1,
                            'markets/{id}' => 1,
                            'public-search' => 1,
                        ),
                    ),
                ),
                'clob' => array(
                    'public' => array(
                        'get' => array(
                            'book' => 1,
                            'prices-history' => 1,
                            'data/trades' => 1,
                            'price' => 1,
                            'midpoint' => 1,
                            'spread' => 1,
                        ),
                    ),
                    'private' => array(
                        'get' => array(
                            'data/orders' => 1,
                            'data/order/{id}' => 1,
                        ),
                        'post' => array(
                            'order' => 1,
                        ),
                        'delete' => array(
                            'order' => 1,
                            'orders' => 1,
                        ),
                    ),
                ),
                'data' => array(
                    'private' => array(
                        'get' => array(
                            'positions' => 1,
                            'trades' => 1,
                            'value' => 1,
                        ),
                    ),
                ),
            ),
            'requiredCredentials' => array(
                'apiKey' => true,   // POLY_API_KEY
                'secret' => true,   // POLY_API_SECRET
                'password' => true,   // POLY_PASSPHRASE
                'walletAddress' => true,   // Ethereum wallet address
            ),
            'fees' => array(
                'trading' => array(
                    'tierBased' => false,
                    'percentage' => true,
                    'maker' => 0.0,
                    'taker' => 0.0,
                ),
            ),
            'options' => array(
                'defaultFetchEventsLimit' => 100,
                'maxFetchEventsLimit' => 500,
                'defaultEventStatus' => 'active',  // 'active' | 'closed' | 'all'
            ),
        ));
    }

    public function fetch_markets(array $params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            $queries = $this->safe_list($params, 'queries', array());
            $rest0 = $this->omit($params, array( 'queries' ));
            $pageSize = 0;
            $flatMarkets => Marketarray() = array();
            $eventsDict = array();
            if ($queries && strlen($queries) > 0) {
                $pageSize = $this->safe_integer($rest0, 'limit', 50);
                $searchRest = $this->omit($rest0, array( 'limit' ));
                $seen = array();
                $rawEvents => anyarray() = array();
                for ($qi = 0; $qi < count($queries); $qi++) {
                    $q = $queries[$qi];
                    $baseRequest1 = array( 'q' => $q, 'limit_per_type' => $pageSize, 'events_status' => 'active' );
                    $firstRequest = array( 'page' => 1 );
                    $firstRequest = $this->extend($firstRequest, $baseRequest1, $searchRest);
                    $first = Async\await($this->gammaPublicGetPublicSearch ($firstRequest));
                    $firstEvents = $this->safe_list($first, 'events', array());
                    $pagination = $this->safe_value($first, 'pagination', array());
                    $totalResults = $this->safe_integer($pagination, 'totalResults', strlen($firstEvents));
                    $totalPages = (int) ceil($totalResults / $pageSize);
                    $remaining => numberarray() = array();
                    for ($p = 2; $p <= $totalPages; $p++) {
                        $remaining[] = $p;
                    }
                    $restPromises => anyarray() = array();
                    for ($pi = 0; $pi < count($remaining); $pi++) {
                        $pageRequest = array( 'page' => $remaining[$pi] );
                        $pageRequest = $this->extend($pageRequest, $baseRequest1, $searchRest);
                        $restPromises[] = $this->gammaPublicGetPublicSearch ($pageRequest);
                    }
                    $restResponses = Async\await(Promise\all($restPromises));
                    $allEvents => anyarray() = array();
                    for ($fi = 0; $fi < count($firstEvents); $fi++) {
                        $allEvents[] = $firstEvents[$fi];
                    }
                    for ($ri = 0; $ri < count($restResponses); $ri++) {
                        $pageEvents = $this->safe_list($restResponses[$ri], 'events', array());
                        for ($ei = 0; $ei < count($pageEvents); $ei++) {
                            $allEvents[] = $pageEvents[$ei];
                        }
                    }
                    for ($ei = 0; $ei < count($allEvents); $ei++) {
                        $rawEvent = $allEvents[$ei];
                        $eventId = $this->safe_string($rawEvent, 'id');
                        if ($eventId && !$seen[$eventId]) {
                            $seen[$eventId] = true;
                            $rawEvents[] = $rawEvent;
                        }
                    }
                }
                for ($rei = 0; $rei < count($rawEvents); $rei++) {
                    $rawEvent = $rawEvents[$rei];
                    $ccxtMarkets = $this->parse_event_to_markets($rawEvent);
                    for ($mi = 0; $mi < count($ccxtMarkets); $mi++) {
                        $flatMarkets[] = $ccxtMarkets[$mi];
                    }
                    $parsedEvent = $this->parse_event($rawEvent);
                    $eventSlug = $this->safe_string($rawEvent, 'slug');
                    if ($eventSlug) {
                        $eventKey = $this->shorten_slugeventSlug;
                        $eventsDict[$eventKey] = $parsedEvent;
                    }
                }
                $this->events = $eventsDict;
                return $flatMarkets;
            }
            $pageSize = $this->safe_integer($this->options, 'maxFetchEventsLimit', 500);
            $maxPages = 20;
            $status = $this->safe_string($rest0, 'status', $this->safe_string($this->options, 'defaultEventStatus', 'active'));
            $rest = $this->omit($rest0, array( 'status' ));
            $baseRequest = array( 'limit' => $pageSize, 'order' => 'volume24hr', 'ascending' => false );
            $baseRequest = $this->extend($baseRequest, $rest);
            if ($status === 'active') {
                $baseRequest['active'] = true;
            } elseif ($status === 'closed') {
                $baseRequest['closed'] = true;
            }
            // Fetch $page 1 $first; if full, fire $remaining pages in parallel
            $firstPageRequest = array( 'offset' => 0 );
            $firstPageRequest = $this->extend($firstPageRequest, $baseRequest);
            $firstPageResponse = Async\await($this->gammaPublicGetEvents ($firstPageRequest));
            $firstPage = ($firstPageResponse || array());
            $allRawEvents => anyarray() = array();
            for ($fi = 0; $fi < count($firstPage); $fi++) {
                $allRawEvents[] = $firstPage[$fi];
            }
            if (strlen($firstPage) >= $pageSize) {
                $offsets => numberarray() = array();
                for ($p = 1; $p < $maxPages; $p++) {
                    $offsets[] = $p * $pageSize;
                }
                $restPromises2 => anyarray() = array();
                for ($oi = 0; $oi < count($offsets); $oi++) {
                    $pageRequest = array( 'offset' => $offsets[$oi] );
                    $pageRequest = $this->extend($pageRequest, $baseRequest);
                    $restPromises2[] = $this->gammaPublicGetEvents ($pageRequest);
                }
                $restPages = Async\await(Promise\all($restPromises2));
                for ($ri2 = 0; $ri2 < count($restPages); $ri2++) {
                    $page = ($restPages[$ri2] || array());
                    for ($pi2 = 0; $pi2 < count($page); $pi2++) {
                        $allRawEvents[] = $page[$pi2];
                    }
                }
            }
            for ($rei = 0; $rei < count($allRawEvents); $rei++) {
                $rawEvent = $allRawEvents[$rei];
                $ccxtMarkets = $this->parse_event_to_markets($rawEvent);
                for ($mi = 0; $mi < count($ccxtMarkets); $mi++) {
                    $flatMarkets[] = $ccxtMarkets[$mi];
                }
                $parsedEvent = $this->parse_event($rawEvent);
                $eventSlug = $this->safe_string($rawEvent, 'slug');
                if ($eventSlug) {
                    $eventKey = $this->shorten_slugeventSlug;
                    $eventsDict[$eventKey] = $parsedEvent;
                }
            }
            $this->events = $eventsDict;
            return $flatMarkets;
        }) ();
    }

    public function parse_event_to_markets(array $event): array {
        $eventSlug = $this->safe_string($event, 'slug', $this->safe_string($event, 'id'));
        $rawMarkets = $this->safe_list($event, 'markets', array());
        $result => Marketarray() = array();
        //
        // {
        //    "id":"604489",
        //    "question":"Will Trump visit China by October 31?",
        //    "conditionId":"0x3d69cc559693ee46ba58da16e43c4e75b8da67b99c2e9a9d2f72bb0222d0f137",
        //    "slug":"will-trump-visit-china-by-october-31",
        //    "resolutionSource":"",
        //    "endDate":"2025-10-31T00:00:00Z",
        //    "startDate":"2025-09-19T21:22:54.912576Z",
        //    "image":"https://polymarket-upload.s3.us-east-2.amazonaws.com/will-trump-visit-china-by-october-31-ujqWMja0Uizt.png",
        //    "icon":"https://polymarket-upload.s3.us-east-2.amazonaws.com/will-trump-visit-china-by-october-31-ujqWMja0Uizt.png",
        //    "description":"If U.S. President Donald Trump visits China by October 31, 2025, 11:59 PM ET, this $market will resolve to \\""Yes\\"". Otherwise, this $market will resolve to \\""No\\"".\\n\\nFor the purpose of this $market, a \\""visit\\"" is defined physically entering the terrestrial or maritime territory of the listed country. Whether or not Trump enters the country's airspace during the timeframe of this $market will have no bearing on a positive resolution.\\n\\nThe primary resolution source for this information will be official information from government of the United States of America, official information from Trump or released by his verified social media accounts (e.g. https://twitter.com/POTUS), however, a consensus of credible reporting will also be used.",
        //    "outcomes":"[\\""Yes\\"", \\""No\\""]",
        //    "outcomePrices":"[\\"0\\", \\"1\\"]",
        //    "volume":"549414.493468",
        //    "active":true,
        //    "closed":true,
        //    "marketMakerAddress":"",
        //    "createdAt":"2025-09-19T19:32:28.841694Z",
        //    "updatedAt":"2026-03-09T22:44:28.896812Z",
        //    "closedTime":"2025-11-01 06:28:08+00",
        //    "new":false,
        //    "featured":false,
        //    "submitted_by":"0x91430CaD2d3975766499717fA0D66A78D814E5c5",
        //    "archived":false,
        //    "resolvedBy":"0x65070BE91477460D8A7AeEb94ef92fe056C2f2A7",
        //    "restricted":true,
        //    "groupItemTitle":"October 31, 2025",
        //    "groupItemThreshold":"0",
        //    "questionID":"0x2dd49c70f01a5e7c687a9820d606ff0d85fb50199735928d52d98b3a57586969",
        //    "umaEndDate":"2025-11-01T06:28:08Z",
        //    "enableOrderBook":true,
        //    "orderPriceMinTickSize":"0.001",
        //    "orderMinSize":"5",
        //    "umaResolutionStatus":"resolved",
        //    "volumeNum":"549414.493468",
        //    "endDateIso":"2025-10-31",
        //    "startDateIso":"2025-09-19",
        //    "hasReviewedDates":true,
        //    "volume1wk":"121949.66579699998",
        //    "volume1mo":"535231.3545640002",
        //    "volume1yr":"549414.4934680002",
        //    "clobTokenIds":"[\\"45601394554497090173642354630373884477724604907691447337031201817815960365378\\", \\"102652665954921241745169157447280060113772926009745753029489061659654862632571\\"]",
        //    "umaBond":"500",
        //    "umaReward":"5",
        //    "volume1wkClob":"121949.66579699998",
        //    "volume1moClob":"535231.3545640002",
        //    "volume1yrClob":"549414.4934680002",
        //    "volumeClob":"549414.493468",
        //    "customLiveness":"0",
        //    "acceptingOrders":false,
        //    "negRisk":false,
        //    "negRiskRequestID":"",
        //    "ready":false,
        //    "funded":false,
        //    "acceptingOrdersTimestamp":"2025-09-19T21:22:32Z",
        //    "cyom":false,
        //    "pagerDutyNotificationEnabled":false,
        //    "approved":true,
        //    "rewardsMinSize":"100",
        //    "rewardsMaxSpread":"3.5",
        //    "spread":"0.001",
        //    "automaticallyResolved":true,
        //    "oneDayPriceChange":"-0.0005",
        //    "oneWeekPriceChange":"-0.007",
        //    "oneMonthPriceChange":"-0.011",
        //    "lastTradePrice":"1",
        //    "bestAsk":"0.001",
        //    "automaticallyActive":true,
        //    "clearBookOnStart":true,
        //    "seriesColor":"",
        //    "showGmpSeries":false,
        //    "showGmpOutcome":false,
        //    "manualActivation":false,
        //    "negRiskOther":false,
        //    "umaResolutionStatuses":"[\\""proposed\\""]",
        //    "pendingDeployment":false,
        //    "deploying":false,
        //    "deployingTimestamp":"2025-09-19T21:22:01.979023Z",
        //    "rfqEnabled":false,
        //    "holdingRewardsEnabled":false,
        //    "feesEnabled":false,
        //    "requiresTranslation":false,
        //    "feeType":null
        // }
        //
        for ($mi = 0; $mi < count($rawMarkets); $mi++) {
            $market = $rawMarkets[$mi];
            $conditionId = $this->safe_string($market, 'conditionId');
            $marketId = $this->safe_string($market, 'id');
            $marketSlug = $this->safe_string($market, 'slug', $conditionId);
            $active = $this->safe_bool($market, 'active', false);
            $closed = $this->safe_bool($market, 'closed', false);
            $tickSize = $this->safe_number($market, 'minimumTickSize', 0.01);
            $endDate = $this->safe_string($market, 'endDate', $this->safe_string($market, 'end_date_iso'));
            // Gamma API returns these arrays-encoded strings
            $outcomeLabels => stringarray() = array();
            $clobTokenIds => stringarray() = array();
            $outcomePrices => stringarray() = array();
            $parsedOutcomes = $this->parse_json($this->safe_string($market, 'outcomes', '[]'));
            $parsedTokenIds = $this->parse_json($this->safe_string($market, 'clobTokenIds', '[]'));
            $parsedPrices = $this->parse_json($this->safe_string($market, 'outcomePrices', '[]'));
            if ($parsedOutcomes && (strlen($parsedOutcomes)) !== null) {
                $outcomeLabels = $parsedOutcomes;
            }
            if ($parsedTokenIds && (strlen($parsedTokenIds)) !== null) {
                $clobTokenIds = $parsedTokenIds;
            }
            if ($parsedPrices && (strlen($parsedPrices)) !== null) {
                $outcomePrices = $parsedPrices;
            }
            if (strlen($outcomeLabels) === 0 || strlen($clobTokenIds) === 0) {
                continue;
            }
            // Market symbol (no outcome suffix)
            $marketSymbol = $this->slug_to_market_symbol($eventSlug, $marketSlug);
            // Build $outcomes array
            $outcomes => anyarray() = array();
            for ($oi = 0; $oi < count($outcomeLabels); $oi++) {
                $outcomeLabel = $outcomeLabels[$oi];
                $clobTokenId = $clobTokenIds[$oi];
                $outcomePrice = $this->safe_number($outcomePrices, $oi);
                if (!$clobTokenId) {
                    continue;
                }
                $outcomes[] = array(
                    'id' => $clobTokenId,
                    'symbol' => $marketSymbol . ':' . strtoupper($outcomeLabel),
                    'marketSymbol' => $marketSymbol,
                    'label' => $outcomeLabel,
                    'price' => $outcomePrice,
                    'active' => $active && !$closed,
                    'info' => $market,
                );
            }
            $result[] = array(
                'id' => $conditionId,
                'symbol' => $marketSymbol,
                'base' => 'USDC',
                'quote' => 'USDC',
                'settle' => null,
                'baseId' => $conditionId || $marketId,
                'quoteId' => 'USDC',
                'settleId' => null,
                'type' => 'prediction',
                'spot' => false,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'prediction' => true,
                'active' => $active && !$closed,
                'contract' => false,
                'linear' => null,
                'inverse' => null,
                'contractSize' => null,
                'expiry' => $endDate ? $this->parse8601($endDate) : null,
                'expiryDatetime' => $endDate,
                'strike' => null,
                'optionType' => null,
                'taker' => 0.0,
                'maker' => 0.0,
                'percentage' => true,
                'tierBased' => false,
                'feeSide' => 'get',
                'precision' => array(
                    'amount' => $tickSize,
                    'price' => $tickSize,
                ),
                'limits' => array(
                    'leverage' => array( 'min' => 1, 'max' => 1 ),
                    'amount' => array( 'min' => 1, 'max' => null ),
                    'price' => array( 'min' => 0.01, 'max' => 0.99 ),
                    'cost' => array( 'min' => null, 'max' => null ),
                ),
                'outcomes' => $outcomes,
                'info' => $market,
                'created' => null,
            );
        }
        return $result;
    }

    public function fetch_ticker(string $outcome, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $params) {
            /**
             * Fetches the current mid-price and best bid/ask for a single $outcome token.
             * @param $outcome
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/data/get-midpoint-price
             * @see https://docs.polymarket.com/api-reference/market-data/get-order-book
             *
             */
            Async\await($this->load_markets());
            $outcomeObj = $this->outcome($outcome);
            $tokenId = $outcomeObj['id'];
            // Sequential to avoid Promise\all(is_array(lib scope) && array_key_exists(not, lib scope))
            $midpointResponse = Async\await($this->clobPublicGetMidpoint (array( 'token_id' => $tokenId )));
            $bookResponse = Async\await($this->clobPublicGetBook (array( 'token_id' => $tokenId )));
            return $this->parse_ticker(
                array( 'midpoint' => $midpointResponse, 'book' => $bookResponse ),
                $outcomeObj
            );
        }) ();
    }

    public function fetch_tickers(?array $outcomes, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcomes, $params) {
            /**
             * Fetches tickers for multiple outcome tokens sequentially.
             * @param $outcomes
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/data/get-midpoint-price
             *
             */
            Async\await($this->load_markets());
            $targets => stringarray() = $outcomes ? ($outcomes) : is_array($this->outcomes || array()) ? array_keys($this->outcomes || array()) : array();
            $result => Tickers = array();
            for ($outcomeSymbol of $targets) {
                $ticker = Async\await($this->fetch_ticker($outcomeSymbol, $params));
                $result[$outcomeSymbol] = $ticker;
            }
            return $result;
        }) ();
    }

    public function parse_ticker(array $ticker, ?array $market = null): array {
        /**
         * Parses a combined midpoint . order book response into a unified CCXT Ticker object.
         * @param $ticker
         * @param $market
         */
        $midpointData = $this->safe_value($ticker, 'midpoint', array());
        $bookData = $this->safe_value($ticker, 'book', array());
        $mid = $this->safe_number($midpointData, 'mid');
        $bids = $this->safe_list($bookData, 'bids', array());
        $asks = $this->safe_list($bookData, 'asks', array());
        $bestBid = strlen($bids) ? $this->safe_number($bids[0], 'price') : null;
        $bestAsk = strlen($asks) ? $this->safe_number($asks[0], 'price') : null;
        $symbol = $this->safe_symbol(null, $market);
        $now = $this->milliseconds();
        return $this->safe_ticker(array(
            'symbol' => $symbol,
            'timestamp' => $now,
            'datetime' => $this->iso8601($now),
            'high' => null,
            'low' => null,
            'bid' => $bestBid,
            'bidVolume' => strlen($bids) ? $this->safe_number($bids[0], 'size') : null,
            'ask' => $bestAsk,
            'askVolume' => strlen($asks) ? $this->safe_number($asks[0], 'size') : null,
            'vwap' => null,
            'open' => null,
            'close' => $mid,
            'last' => $mid,
            'previousClose' => null,
            'change' => null,
            'percentage' => null,
            'average' => $mid,
            'baseVolume' => null,
            'quoteVolume' => $market ? $this->safe_number($market['info'], 'volume24h') : null,
            'info' => $ticker,
        ), $market);
    }

    public function fetch_order_book(string $outcome, ?int $limit = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $limit, $params) {
            /**
             * Fetches the CLOB order book for a single $outcome token.
             * @param $outcome
             * @param $limit
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/market-data/get-order-book
             *
             */
            Async\await($this->load_markets());
            $outcomeObj = $this->outcome($outcome);
            $tokenId = $outcomeObj['id'];
            $request = array(
                'token_id' => $tokenId,
            );
            $response = Async\await($this->clobPublicGetBook ($this->extend($request, $params)));
            $timestamp = $this->milliseconds();
            return $this->parse_order_book($response, $outcome, $timestamp, 'bids', 'asks', 'price', 'size');
        }) ();
    }

    public function fetch_ohlcv(string $outcome, $timeframe = '1m', ?int $since = null, ?int $limit = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $timeframe, $since, $limit, $params) {
            /**
             * Fetches price $history ticks for a single $outcome token and maps them to OHLCV format.
             * @param $outcome
             * @param $timeframe
             * @param $since
             * @param $limit
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/markets/get-prices-$history
             *
             */
            Async\await($this->load_markets());
            $outcomeObj = $this->outcome($outcome);
            $tokenId = $outcomeObj['id'];
            $fidelity = $this->safe_string($this->timeframes, $timeframe, '1');
            $request = array(
                'market' => $tokenId,
                'fidelity' => $fidelity,
            );
            if ($since !== null) {
                $request['startTs'] = $this->parse_to_int($since / 1000);
            }
            if ($limit !== null && $since !== null) {
                $tf = $this->parse_timeframe($timeframe);
                $endS = ($since / 1000) . $limit * $tf;
                $nowS = $this->seconds();
                $request['endTs'] = $endS < $nowS ? $endS : $nowS;
            }
            $response = Async\await($this->clobPublicGetPricesHistory ($this->extend($request, $params)));
            $history = $this->safe_list($response, 'history', array());
            return $this->parse_ohlcvs($history, $outcomeObj, $timeframe, $since, $limit);
        }) ();
    }

    public function parse_ohlcv(array $ohlcv, ?array $market = null): array {
        /**
         * Parses a single Polymarket prices-history tick `array( t, p )` into a CCXT OHLCV tuple.
         * @param $ohlcv
         * @param $market
         */
        // Polymarket prices-history tick => array( t => unix_seconds, p => $price )
        $ts = $this->safe_integer($ohlcv, 't');
        $price = $this->safe_number($ohlcv, 'p');
        return array(
            $ts !== null ? $ts * 1000 : null,
            $price,   // open  (raw tick — no OHLCV disaggregation available)
            $price,   // high
            $price,   // low
            $price,   // close
            null, // volume (not provided per-tick)
        );
    }

    public function fetch_trades(string $outcome, ?int $since = null, ?int $limit = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $since, $limit, $params) {
            /**
             * Fetches public trade history for a single $outcome token from the CLOB data endpoint.
             * @param $outcome
             * @param $since
             * @param $limit
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/trade/get-$trades
             *
             */
            Async\await($this->load_markets());
            $outcomeObj = $this->outcome($outcome);
            $tokenId = $outcomeObj['id'];
            $request = array( 'asset_id' => $tokenId );
            if ($limit !== null) {
                $request['limit'] = $limit;
            }
            $response = Async\await($this->clobPublicGetDataTrades ($this->extend($request, $params)));
            $trades = $this->safe_list($response, 'data', array());
            return $this->parse_trades($trades, $outcomeObj, $since, $limit);
        }) ();
    }

    public function parse_trade(array $trade, ?array $market = null): array {
        /**
         * Parses a raw CLOB $trade object into a unified CCXT Trade object.
         * @param $trade
         * @param $market
         */
        $id = $this->safe_string($trade, 'id');
        $timestamp = $this->safe_integer_product($trade, 'timestamp', 1000);
        $price = $this->safe_number($trade, 'price');
        $amount = $this->safe_number($trade, 'size');
        $rawSide = $this->safe_string_lower($trade, 'side');
        $side = ($rawSide === 'buy' || $rawSide === 'sell') ? $rawSide : null;
        $symbol = $this->safe_symbol(null, $market);
        return $this->safe_trade(array(
            'id' => $id,
            'info' => $trade,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'symbol' => $symbol,
            'order' => $this->safe_string($trade, 'orderId'),
            'type' => null,
            'side' => $side,
            'takerOrMaker' => null,
            'price' => $price,
            'amount' => $amount,
            'cost' => null,
            'fee' => null,
        ), $market);
    }

    public function fetch_balance(array $params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            /**
             * Fetches the authenticated user's USDC portfolio value from the Data API.
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/core/get-total-value-of-a-users-positions
             *
             */
            $request = array(
                'user' => $this->walletAddress,
            );
            $response = Async\await($this->dataPrivateGetValue ($this->extend($request, $params)));
            return $this->parse_balance($response);
        }) ();
    }

    public function parse_balance(array $response): array {
        /**
         * Parses a portfolio value $response into a CCXT Balances object with a USDC entry.
         * @param $response
         */
        $result = array( 'info' => $response );
        $total = $this->safe_number($response, 'value', $this->safe_number($response, 'total'));
        $result['USDC'] = array(
            'free' => $total,
            'used' => 0,
            'total' => $total,
        );
        return $result;
    }

    public function fetch_positions(?array $outcomes = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcomes, $params) {
            /**
             * Fetches open outcome token $positions for the authenticated user from the Data API.
             * @param $outcomes
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/core/get-current-$positions-for-a-user
             *
             */
            if ($this->walletAddress === null) {
                throw new ArgumentsRequired($this->id . ' walletAddress is required to fetchPositions');
            }
            $request = array(
                'user' => $this->walletAddress,
            );
            $response = Async\await($this->dataPrivateGetPositions ($this->extend($request, $params)));
            $positions = $this->safe_list($response, 'data', array());
            return $this->parse_positions($positions, $outcomes);
        }) ();
    }

    public function parse_position(array $position, ?array $market = null): array {
        /**
         * Parses a raw Data API $position object into a unified CCXT Position object.
         * @param $position
         * @param $market
         */
        $tokenId = $this->safe_string($position, 'asset');
        $marketData = $this->safe_outcome($tokenId, $market);
        $size = $this->safe_number($position, 'size');
        $entryPrice = $this->safe_number($position, 'avgPrice');
        $curPrice = $this->safe_number($position, 'currentPrice');
        // $unrealizedPnl = ($size !== null && $entryPrice !== null && $curPrice !== null)
        //     ? $size * ($curPrice - $entryPrice)
        //     : null;
        return array(
            'id' => $this->safe_string($position, 'id'),
            'symbol' => $marketData['symbol'],
            'timestamp' => null,
            'datetime' => null,
            'contracts' => $size,
            'contractSize' => 1,
            'side' => 'long',
            'notional' => ($size !== null && $curPrice !== null) ? $size * $curPrice : null,
            'leverage' => 1,
            'unrealizedPnl' => null,
            'realizedPnl' => $this->safe_number($position, 'realizedPnl'),
            'collateral' => null,
            'entryPrice' => $entryPrice,
            'markPrice' => $curPrice,
            'liquidationPrice' => null,
            'hedged' => false,
            'maintenanceMargin' => null,
            'maintenanceMarginPercentage' => null,
            'initialMargin' => null,
            'initialMarginPercentage' => null,
            'marginRatio' => null,
            'marginMode' => 'cross',
            'marginType' => 'cross',
            'percentage' => null,
            'info' => $position,
        );
    }

    public function fetch_open_orders(?string $outcome = null, ?int $since = null, ?int $limit = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $since, $limit, $params) {
            /**
             * Fetches open resting $orders for the authenticated user, optionally filtered by $outcome token.
             * @param $outcome
             * @param $since
             * @param $limit
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/trade/get-user-$orders
             *
             */
            $request = array();
            $outcomeObj = null;
            if ($outcome !== null) {
                $outcomeObj = $this->outcome($outcome);
                $request['asset_id'] = $outcomeObj['id'];
            }
            $response = Async\await($this->clobPrivateGetDataOrders ($this->extend($request, $params)));
            $orders = $this->safe_list($response, 'data', array());
            return $this->parse_orders($orders, $outcomeObj, $since, $limit);
        }) ();
    }

    public function fetch_order(?string $id, ?string $outcome = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($id, $outcome, $params) {
            /**
             * Fetches a single order by ID from the CLOB private data endpoint.
             * @param $id
             * @param symbol
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/trade/get-single-order-by-$id
             *
             */
            $request = array( 'id' => $id );
            $response = Async\await($this->clobPrivateGetDataOrderId ($this->extend($request, $params)));
            return $this->parse_order($response);
        }) ();
    }

    public function parse_order(array $order, ?array $market = null): array {
        /**
         * Parses a raw CLOB $order object into a unified CCXT Order object.
         * @param $order
         * @param $market
         */
        $id = $this->safe_string($order, 'id');
        $tokenId = $this->safe_string($order, 'asset_id');
        $mkt = $this->safe_outcome($tokenId, $market);
        $status = $this->parse_order_status($this->safe_string($order, 'status'));
        $side = $this->safe_string_lower($order, 'side');
        $price = $this->safe_number($order, 'price');
        $amount = $this->safe_number($order, 'original_size');
        $filled = $this->safe_number($order, 'size_matched', 0);
        $ts = $this->safe_integer_product($order, 'created_at', 1000);
        return $this->safe_order(array(
            'id' => $id,
            'clientOrderId' => null,
            'info' => $order,
            'timestamp' => $ts,
            'datetime' => $this->iso8601($ts),
            'lastTradeTimestamp' => null,
            'status' => $status,
            'symbol' => $mkt['symbol'],
            'type' => $this->safe_string_lower($order, 'type', 'limit'),
            'timeInForce' => $this->safe_string($order, 'time_in_force', 'GTC'),
            'postOnly' => null,
            'side' => $side,
            'price' => $price,
            'stopPrice' => null,
            'triggerPrice' => null,
            'average' => null,
            'amount' => $amount,
            'cost' => null,
            'filled' => $filled,
            'remaining' => null,
            'fee' => null,
            'trades' => array(),
        ), $mkt);
    }

    public function parse_order_status(?string $status): ?string {
        /**
         * Maps a Polymarket order $status string to the CCXT unified $status vocabulary.
         * @param $status
         */
        $statuses = array(
            'LIVE' => 'open',
            'MATCHED' => 'closed',
            'CANCELLED' => 'canceled',
            'DELAYED' => 'open',
        );
        return $this->safe_string($statuses, $status, $status);
    }

    public function create_order(string $outcome, ?string $type, ?string $side, ?float $amount, ?float $price = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $type, $side, $amount, $price, $params) {
            /**
             * Places a limit or market order on the Polymarket CLOB for the given $outcome token.
             * @param $outcome
             * @param $type
             * @param $side
             * @param $amount
             * @param $price
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/trade/post-a-new-order
             *
             */
            Async\await($this->load_markets());
            $outcomeObj = $this->outcome($outcome);
            $tokenId = $outcomeObj['id'];
            $sideStr = strtoupper($side);
            $typeStr = strtoupper($type);
            $request = array(
                'token_id' => $tokenId,
                'price' => $price,
                'size' => $amount,
                'side' => $sideStr,
                'type' => $typeStr,
            );
            $response = Async\await($this->clobPrivatePostOrder ($this->extend($request, $params)));
            return $this->parse_order($response, $outcomeObj);
        }) ();
    }

    public function cancel_order(?string $id, ?string $outcome = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($id, $outcome, $params) {
            /**
             * Cancels a single open order by ID on the Polymarket CLOB.
             * @param $id
             * @param symbol
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/trade/cancel-single-order
             *
             */
            $request = array( 'order_id' => $id );
            $response = Async\await($this->clobPrivateDeleteOrder ($this->extend($request, $params)));
            return $this->parse_order($response);
        }) ();
    }

    public function cancel_all_orders(?string $outcome = null, array $params = array ()): PromiseInterface {
        return Async\async(function () use ($outcome, $params) {
            /**
             * Cancels all open orders on the Polymarket CLOB, optionally scoped to one $outcome token.
             * @param $outcome
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/trade/cancel-all-orders
             *
             */
            $request = array();
            if ($outcome !== null) {
                $outcomeObj = $this->outcome($outcome);
                $request['asset_id'] = $outcomeObj['id'];
            }
            $response = Async\await($this->clobPrivateDeleteOrders ($this->extend($request, $params)));
            return $this->parse_orders($response);
        }) ();
    }

    public function fetch_events(array $queries = [], array $params = array ()): PromiseInterface {
        return Async\async(function () use ($queries, $params) {
            /**
             * Fetches events matching the given search terms via the Gamma public-search endpoint and
             * merges them into $this->events and $this->markets; with no $queries, fetches all active events.
             * Returns the full $this->events dict (all cached events, not just the newly fetched ones).
             * @param $queries
             * @param $params
             *
             * @see https://docs.polymarket.com/api-reference/search/search-markets-events-and-profiles
             *
             */
            $pageSize = $this->safe_integer($params, 'limit', 50);
            $rest = $this->omit($params, array( 'limit' ));
            // For each query => fetch page 1, then all remaining pages in parallel
            $seen = array();
            $rawEvents => anyarray() = array();
            for ($q of $queries) {
                $baseRequest = array( 'q' => $q, 'limit_per_type' => $pageSize, 'events_status' => 'active' );
                $firstRequest = array( 'page' => 1 );
                $first = Async\await($this->gammaPublicGetPublicSearch ($this->extend($firstRequest, $baseRequest, $rest)));
                $firstEvents = $this->safe_list($first, 'events', array());
                $pagination = $this->safe_value($first, 'pagination', array());
                $totalResults = $this->safe_integer($pagination, 'totalResults', strlen($firstEvents));
                $totalPages = (int) ceil($totalResults / $pageSize);
                $remainingPages => numberarray() = array();
                for ($p = 2; $p <= $totalPages; $p++) {
                    $remainingPages[] = $p;
                }
                $restPromises3 => anyarray() = array();
                for ($pi3 = 0; $pi3 < count($remainingPages); $pi3++) {
                    $pageRequest = array( 'page' => $remainingPages[$pi3] );
                    $restPromises3[] = $this->gammaPublicGetPublicSearch ($this->extend($pageRequest, $baseRequest, $rest));
                }
                $restResponses = Async\await(Promise\all($restPromises3));
                $allEvents => anyarray() = ($firstEvents).slice ();
                for ($ri3 = 0; $ri3 < count($restResponses); $ri3++) {
                    $pageEvents3 = $this->safe_list($restResponses[$ri3], 'events', array());
                    for ($ei3 = 0; $ei3 < count($pageEvents3); $ei3++) {
                        $allEvents[] = $pageEvents3[$ei3];
                    }
                }
                for ($rawEvent of $allEvents) {
                    $eventId = $this->safe_string($rawEvent, 'id');
                    if ($eventId && !$seen[$eventId]) {
                        $seen[$eventId] = true;
                        $rawEvents[] = $rawEvent;
                    }
                }
            }
            // Parse and merge into class-level caches
            if (!$this->events) {
                $this->events = array();
            }
            if (!$this->markets) {
                $this->markets = array();
            }
            for ($rawEvent of $rawEvents) {
                $ccxtMarkets = $this->parse_event_to_markets($rawEvent);
                for ($m of $ccxtMarkets) {
                    $this->markets[$m['symbol']] = $m;
                }
                $parsedEvent = $this->parse_event($rawEvent, $ccxtMarkets);
                $eventSlug = $this->safe_string($rawEvent, 'slug');
                if ($eventSlug) {
                    $eventKey = $this->shorten_slugeventSlug;
                    $this->events[$eventKey] = $parsedEvent;
                }
            }
            return is_array($this->events) ? array_values($this->events) : array();
        }) ();
    }

    public function parse_event(array $rawEvent): array {
        // {
        //     "id" => "73113",
        //     "ticker" => "ukraine-agrees-not-to-join-nato-before-2027",
        //     "slug" => "ukraine-agrees-not-to-join-nato-before-2027",
        //     "title" => "Ukraine agrees not to join NATO before 2027? ",
        //     "description" => "This market will resolve to \\"Yes\\" if Ukraine publicly agrees not to join NATO by December 31, 2026, 11:59 PM ET. Otherwise, this market will resolve to “No”.\\n\\nAn official pledge by Ukraine not to join NATO will qualify for a “Yes” resolution whether unilateral announcement or part of an agreement with the Russian Federation.\\n\\nAny agreement or pledge made before the resolution date of this market will qualify, regardless of if/when the agreement goes into effect.\\n\\nAn agreement by Ukraine not to join NATO for any amount of time will count (e.g. If Ukraine not to join NATO for 10 years this will qualify).\\n\\nAn agreement by Ukraine not to join NATO precondition of a more comprehensive peace process or deal will qualify, even if the agreement is not finalized or part of a formalized peace deal. The September 8, 1995 “Agreed Basic Principles” between Bosnia and Yugoslavia which recognized the borders and sovereignty of Bosnia and Herzegovina, and was later formalized through the Dayton Peace Agreement is an example of a qualifying agreement. \\n\\nThe primary resolution source for this market will be an official announcement by the Ukraine, however an overwhelming consensus of credible reporting confirming a qualifying agreement has been reached will also count.",
        //     "resolutionSource" => "",
        //     "startDate" => "2025-11-05T17:00:57.200353Z",
        //     "creationDate" => "2025-11-05T17:00:57.20035Z",
        //     "endDate" => "2026-12-31T00:00:00Z",
        //     "image" => "https://polymarket-upload.s3.us-east-2.amazonaws.com/ukraine-agrees-not-to-join-nato-before-july-vKEDpScXuAtt.jpg",
        //     "icon" => "https://polymarket-upload.s3.us-east-2.amazonaws.com/ukraine-agrees-not-to-join-nato-before-july-vKEDpScXuAtt.jpg",
        //     "active" => true,
        //     "closed" => false,
        //     "archived" => false,
        //     "new" => false,
        //     "featured" => false,
        //     "restricted" => true,
        //     "liquidity" => "22010.6659",
        //     "openInterest" => "0",
        //     "createdAt" => "2025-11-04T19:27:23.246129Z",
        //     "updatedAt" => "2026-03-14T14:38:21.25643Z",
        //     "competitive" => "0.9538344143456696",
        //     "enableOrderBook" => true,
        //     "liquidityClob" => "22010.6659",
        //     "commentCount" => "0",
        //     "markets" => array(),
        //     "tags" => array(
        //         array(
        //             "id" => "101970",
        //             "label" => "World",
        //             "slug" => "world",
        //             "forceShow" => false,
        //             "createdAt" => "2025-03-19T23:36:08.498099Z",
        //             "updatedAt" => "2026-03-09T22:25:02.420693Z",
        //             "requiresTranslation" => false
        //         ),
        //         {
        //             "id" => "270",
        //             "label" => "putin",
        //             "slug" => "putin",
        //             "publishedAt" => "2023-11-02 21:46:19.507+00",
        //             "createdAt" => "2023-11-02T21:46:19.528Z",
        //             "updatedAt" => "2026-03-09T22:29:44.08742Z",
        //             "requiresTranslation" => false
        //         }
        //     ),
        //     "cyom" => false,
        //     "showAllOutcomes" => true,
        //     "showMarketImages" => true,
        //     "enableNegRisk" => false,
        //     "automaticallyActive" => true,
        //     "seriesSlug" => "ukraine-not-nato",
        //     "negRiskAugmented" => false,
        //     "cumulativeMarkets" => false,
        //     "pendingDeployment" => false,
        //     "deploying" => false,
        //     "requiresTranslation" => false
        // }
        $marketsList = $this->parse_event_to_markets($rawEvent);
        $slug = $this->safe_string($rawEvent, 'slug');
        return $this->extend(array(
            'id' => $this->safe_string($rawEvent, 'id'),
            'slug' => $slug,
            'symbol' => $slug ? $this->shorten_slug($slug) : null,
            'title' => $this->safe_string($rawEvent, 'title'),
            'markets' => $marketsList,
            'url' => $this->safe_string($rawEvent, 'url'),
            'image' => $this->safe_string($rawEvent, 'image_url'),
            'created' => $this->parse8601($this->safe_string($rawEvent, 'created_date_iso')),
            'createdDatetime' => $this->safe_string($rawEvent, 'created_date_iso'),
            'end' => $this->parse8601($this->safe_string($rawEvent, 'end_date_iso')),
            'endDatetime' => $this->safe_string($rawEvent, 'end_date_iso'),
            'category' => $this->safe_string($rawEvent, 'category'),
            'lastUpdatedAt' => $this->parse8601($this->safe_string($rawEvent, 'last_updated_date_iso')),
            'lastUpdatedAtDatetime' => $this->safe_string($rawEvent, 'last_updated_date_iso'),
            'resolutionSource' => $this->safe_string($rawEvent, 'resolution_source'),
            'resolved' => $this->safe_bool($rawEvent, 'resolved'),
            'info' => $rawEvent,
        ));
    }

    public function parse_events(array $rawEvents): array {
        /**
         * Parses an array of raw Gamma event objects into unified CCXT event objects.
         * @param $rawEvents
         */
        $result => anyarray() = array();
        for ($rawEvent of $rawEvents) {
            $result[] = $this->parse_event($rawEvent);
        }
        return $result;
    }

    public function sign(?string $path, mixed $api = 'gamma', $method = 'GET', array $params = array (), ?array $headers = null, ?array $body = null) {
        /**
         * Builds the request URL and attaches HMAC-SHA256 authentication $headers for private endpoints.
         * @param $path
         * @param $api
         * @param $method
         * @param $params
         * @param $headers
         * @param $body
         */
        // $api is either a string ('gamma') or array (['gamma', 'public'])
        $apiGroup = gettype($api) === 'string' ? $api : $api[0];
        $access = gettype($api) === 'string' ? 'public' : $api[1];
        $baseUrls = $this->urls['api'];
        $baseUrl = $this->safe_string($baseUrls, $apiGroup, $baseUrls['gamma']);
        $url = $baseUrl . '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_paramspath);
        $querystring = $this->urlencode($query);
        if ($method === 'GET' && $querystring) {
            $url .= '?' . $querystring;
        }
        $headers = $this->extend(array(
            'Accept' => 'application/json',
            'Content-Type' => 'application/json',
        ), $headers || array());
        if ($access === 'private') {
            $this->check_required_credentials();
            $timestamp = (string) $this->seconds();
            $signature = $this->hmac(
                $this->encode($timestamp . $method . '/' . $path),
                $this->encode($this->secret),
                'sha256',
                'base64'
            );
            $headers = $this->extend($headers, array(
                'POLY_ADDRESS' => $this->walletAddress,
                'POLY_API_KEY' => $this->apiKey,
                'POLY_PASSPHRASE' => $this->password,
                'POLY_SIGNATURE' => $signature,
                'POLY_TIMESTAMP' => $timestamp,
            ));
            if ($method !== 'GET' && $querystring) {
                $body = $query;
            }
        }
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }
}
