# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.kalshi import ImplicitAPI
import asyncio
from ccxt.base.types import Any, Balances, Int, Market, Num, Order, OrderBook, Position, Str, Ticker, Trade
from typing import List


class kalshi(Exchange, ImplicitAPI):

    def describe(self):
        return self.deep_extend(super(kalshi, self).describe(), {
            'id': 'kalshi',
            'name': 'Kalshi',
            'countries': ['US'],
            'rateLimit': 100,
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'cancelAllOrders': True,
                'cancelOrder': True,
                'createOrder': True,
                'fetchBalance': True,
                'fetchCurrencies': False,
                'fetchEvents': True,
                'fetchMarkets': True,
                'fetchOHLCV': True,
                'fetchOpenOrders': True,
                'fetchOrder': True,
                'fetchOrderBook': True,
                'fetchPositions': True,
                'fetchTicker': True,
                'fetchTickers': False,
                'fetchTrades': True,
                'prediction': True,
            },
            'timeframes': {
                '1m': 1,
                '5m': 5,
                '15m': 15,
                '1h': 60,
                '6h': 360,
                '1d': 1440,
            },
            'urls': {
                'logo': 'https://kalshi.com/favicon.ico',
                'api': {
                    'kalshi': 'https://api.elections.kalshi.com/trade-api/v2',
                },
                'test': {
                    'kalshi': 'https://demo-api.kalshi.co/trade-api/v2',
                },
                'www': 'https://kalshi.com',
                'doc': ['https://trading-api.readme.io/reference/getting-started'],
            },
            'api': {
                'kalshi': {
                    'public': {
                        'get': {
                            'events': 1,
                            'events/{event_ticker}': 1,
                            'series': 1,
                            'series/{series_ticker}': 1,
                            'markets': 1,
                            'markets/{ticker}': 1,
                            'markets/{ticker}/orderbook': 1,
                            'markets/{ticker}/trades': 1,
                            'series/{series_ticker}/markets/{ticker}/candlesticks': 1,
                        },
                    },
                    'private': {
                        'get': {
                            'portfolio/balance': 1,
                            'portfolio/orders': 1,
                            'portfolio/orders/{order_id}': 1,
                            'portfolio/positions': 1,
                            'portfolio/fills': 1,
                        },
                        'post': {
                            'portfolio/orders': 1,
                        },
                        'delete': {
                            'portfolio/orders/{order_id}': 1,
                            'portfolio/orders': 1,
                        },
                    },
                },
            },
            'requiredCredentials': {
                'apiKey': True,   # KALSHI-ACCESS-KEY(UUID)
                'privateKey': True,   # RSA PEM private key for signing
            },
            'fees': {
                'trading': {
                    'tierBased': False,
                    'percentage': True,
                    'maker': 0.0,
                    'taker': 0.07,  # 7% fee on profit
                },
            },
            'options': {
                'defaultFetchEventsLimit': 100,
                'maxFetchMarketsLimit': 1000,
                'defaultEventStatus': 'open',  # 'open' | 'closed' | 'settled'
            },
        })

    async def fetch_markets(self, params: dict = {}) -> List[Market]:
        """
 Fetches all Kalshi markets via cursor pagination and maps each binary market to YES and NO CCXT markets.
 @param params

        https://trading-api.readme.io/reference/getmarkets

        """
        queries = self.safe_list(params, 'queries', [])
        rest = self.omit(params, ['queries'])
        lowerQueries: List[str] = []
        for qi in range(0, len(queries)):
            lowerQueries.append((queries[qi]).lower())
        flatMarkets: Market[] = []
        eventsDict: dict = {}
        cursor: Str = None
        limit = self.safe_integer(self.options, 'maxFetchMarketsLimit', 1000)
        while(True):
            request: dict = {'limit': limit}
            if cursor is not None:
                request['cursor'] = cursor
            response = await self.kalshiPublicGetMarkets(self.extend(request, rest))
            rawMarkets = self.safe_list(response, 'markets', [])
            for(raw of rawMarkets) {
                if len(lowerQueries) > 0:
                    ticker = (self.safe_string(raw, 'ticker') or '').lower()
                    title = (self.safe_string(raw, 'title') or '').lower()
                    matches = False
                    for mi in range(0, len(lowerQueries)):
                        if ticker.find(lowerQueries[mi]) != -1 or title.find(lowerQueries[mi]) != -1:
                            matches = True
                            break
                    if not matches:
                        continue
                parsed = self.parseBinaryMarketToOutcomes(raw)
                eventTicker = self.safe_string(raw, 'event_ticker')
                eventTitle = self.safe_string(raw, 'title', eventTicker)
                eventKey = self.shorten_slug(eventTitle) if eventTitle else None
                for(m of parsed) {
                    flatMarkets.append(m)
                    if eventKey:
                        if not eventsDict[eventKey]:
                            eventsDict[eventKey] = {
                                'id': eventTicker,
                                'slug': eventTicker,
                                'symbol': eventKey,
                                'title': eventTitle,
                                'markets': [],
                            }
                        (eventsDict[eventKey])['markets'].append(m)
            cursor = self.safe_string(response, 'cursor')
            if not cursor or len(rawMarkets) < limit:
                break
        self.events = eventsDict
        return flatMarkets

    def parse_market(self, raw: dict) -> Market:
        # {
        #    "can_close_early":true,
        #    "close_time":"2029-07-01T14:00:00Z",
        #    "created_time":"0001-01-01T00:00:00Z",
        #    "early_close_condition":"This market will close and expire early if the event occurs.",
        #    "event_ticker":"KXBALANCE-29",
        #    "expected_expiration_time":"2029-07-01T14:00:00Z",
        #    "expiration_time":"2029-07-01T14:00:00Z",
        #    "expiration_value":"",
        #    "fractional_trading_enabled":false,
        #    "last_price_dollars":"0.1100",
        #    "latest_expiration_time":"2029-07-01T14:00:00Z",
        #    "liquidity_dollars":"0.0000",
        #    "market_type":"binary",
        #    "no_ask_dollars":"0.9000",
        #    "no_bid_dollars":"0.8900",
        #    "no_sub_title":"During Trump's term",
        #    "notional_value_dollars":"1.0000",
        #    "open_interest_fp":"16353.00",
        #    "open_time":"2025-01-03T15:00:00Z",
        #    "previous_price_dollars":"0.0000",
        #    "previous_yes_ask_dollars":"0.0000",
        #    "previous_yes_bid_dollars":"0.0000",
        #    "price_level_structure":"linear_cent",
        #    "price_ranges":[
        #        {
        #            "end":"1.0000",
        #            "start":"0.0000",
        #            "step":"0.0100"
        #        }
        #    ],
        #    "response_price_units":"usd_cent",
        #    "result":"",
        #    "rules_primary":"If there is not a budget deficit for any of fiscal years 2025, 2026, 2027, or 2028, then the market resolves to Yes.",
        #    "rules_secondary":"",
        #    "settlement_timer_seconds":"1800",
        #    "status":"active",
        #    "subtitle":"",
        #    "tick_size":"1",
        #    "ticker":"KXBALANCE-29",
        #    "title":"Will Trump balance the budget?",
        #    "updated_time":"0001-01-01T00:00:00Z",
        #    "volume_24h_fp":"85.00",
        #    "volume_fp":"40208.00",
        #    "yes_ask_dollars":"0.1100",
        #    "yes_ask_size_fp":"",
        #    "yes_bid_dollars":"0.1000",
        #    "yes_bid_size_fp":"",
        #    "yes_sub_title":"During Trump's term"
        # }
        ticker = self.safe_string(raw, 'ticker')
        eventTicker = self.safe_string(raw, 'event_ticker')
        subtitle = self.safe_string(raw, 'subtitle', self.safe_string(raw, 'title'))
        active = self.safe_string(raw, 'status') == 'open'
        endDate = self.safe_string(raw, 'expiration_time')
        volume = self.safe_number(raw, 'volume')
        liquidity = self.safe_number(raw, 'liquidity')
        openInt = self.safe_number(raw, 'open_interest')
        # Derive series ticker: drop last hyphen-segment from event_ticker
        eventParts = eventTicker.split('-') if eventTicker else []
        seriesTicker = len(eventParts) > '-'.join(eventParts[0:-1]) if 1 else eventTicker
        # Market symbol(no outcome suffix)
        marketSymbol = self.slug_to_market_symbol(eventTicker, subtitle or ticker)
        # Build outcomes
        outcomeLabels = ['YES', 'NO']
        outcomeIds = [ticker, ticker + '-NO']
        outcomes: List[Any] = []
        for oi in range(0, len(outcomeLabels)):
            label = outcomeLabels[oi]
            outcomes.append({
                'id': outcomeIds[oi],
                'symbol': marketSymbol + ':' + label,
                'marketSymbol': marketSymbol,
                'label': label,
                'active': active,
                'info': {
                    'ticker': ticker,
                    'eventTicker': eventTicker,
                    'seriesTicker': seriesTicker,
                    'subtitle': subtitle,
                    'outcomeLabel': label,
                    'volume': volume,
                    'liquidity': liquidity,
                    'openInterest': openInt,
                },
            })
        return {
            'id': ticker,
            'symbol': marketSymbol,
            'base': 'USD',
            'quote': 'USD',
            'settle': None,
            'baseId': ticker,
            'quoteId': 'USD',
            'settleId': None,
            'type': 'prediction',
            'spot': False,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'prediction': True,
            'active': active,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': self.parse8601(endDate) if endDate else None,
            'expiryDatetime': endDate,
            'strike': None,
            'optionType': None,
            'taker': 0.07,
            'maker': 0.0,
            'percentage': True,
            'tierBased': False,
            'feeSide': 'get',
            'precision': {
                'amount': 1,
                'price': 0.01,
            },
            'limits': {
                'leverage': {'min': 1, 'max': 1},
                'amount': {'min': 1, 'max': None},
                'price': {'min': 0.01, 'max': 0.99},
                'cost': {'min': None, 'max': None},
            },
            'outcomes': outcomes,
            'info': self.extend(raw, {
                'ticker': ticker,
                'eventTicker': eventTicker,
                'seriesTicker': seriesTicker,
                'subtitle': subtitle,
                'volume': volume,
                'liquidity': liquidity,
                'openInterest': openInt,
            }),
            'created': None,
        }

    async def fetch_ticker(self, outcome: Str, params: dict = {}) -> Ticker:
        """
 Fetches the current market price and bid/ask for a single Kalshi outcome.
 @param outcome
 @param params

        https://trading-api.readme.io/reference/getmarket

        """
        await self.load_markets()
        outcomeObj = self.outcome(outcome)
        ticker = self.safe_string(outcomeObj['info'], 'ticker')
        response = await self.kalshiPublicGetMarketsTicker(self.extend({'ticker': ticker}, params))
        raw = self.safe_value(response, 'market', response)
        return self.parse_ticker(raw, outcomeObj)

    def parse_ticker(self, raw: dict, market: Market = None) -> Ticker:
        """
 Parses a raw Kalshi market object into a unified CCXT Ticker, converting cent prices to decimals.
 @param raw
 @param market
        """
        isNo = (market['label'] == 'NO' or self.safe_string(market['info'], 'outcomeLabel') == 'NO') if market else False
        now = self.milliseconds()
        symbol = self.safe_symbol(None, market)
        # Kalshi prices are in cents(integer 0–99) → divide by 100
        yesAsk = self.safe_number(raw, 'yes_ask')
        yesBid = self.safe_number(raw, 'yes_bid')
        last = self.safe_number(raw, 'last_price')
        bid: Num
        ask: Num
        close: Num
        if isNo:
            bid = (100 - yesAsk) / 100 if (yesAsk is not None) else None
            ask = (100 - yesBid) / 100 if (yesBid is not None) else None
            close = (100 - last) / 100 if (last is not None) else None
        else:
            bid = yesBid / 100 if (yesBid is not None) else None
            ask = yesAsk / 100 if (yesAsk is not None) else None
            close = last / 100 if (last is not None) else None
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': now,
            'datetime': self.iso8601(now),
            'high': None,
            'low': None,
            'bid': bid,
            'bidVolume': None,
            'ask': ask,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': close,
            'last': close,
            'previousClose': None,
            'change': None,
            'percentage': None,
            'average': (bid + ask) / 2 if (bid is not None and ask is not None) else None,
            'baseVolume': None,
            'quoteVolume': self.safe_number(raw, 'volume'),
            'info': raw,
        }, market)

    async def fetch_order_book(self, outcome: Str, limit: Int = None, params: dict = {}) -> OrderBook:
        """
 Fetches the order book for a single Kalshi outcome, converting YES-side cents to decimal prices.
 @param outcome
 @param limit
 @param params

        https://trading-api.readme.io/reference/getmarketorderbook

        """
        await self.load_markets()
        outcomeObj = self.outcome(outcome)
        ticker = self.safe_string(outcomeObj['info'], 'ticker')
        isNo = outcomeObj['label'] == 'NO'
        response = await self.kalshiPublicGetMarketsTickerOrderbook(self.extend({
            'ticker': ticker,
        }, params))
        book = self.safe_value(response, 'orderbook', response)
        timestamp = self.milliseconds()
        # Kalshi uses YES-side perspective: `yes` = bids, `no` = asks(inverted)
        rawYes = self.safe_list(book, 'yes', [])
        rawNo = self.safe_list(book, 'no', [])
        # Convert [price_cents, size] → [price, size]
        bids: List[Any] = []
        asks: Any[] = []
        if isNo:
            # NO perspective: NO bids come from rawNo, NO asks invert rawYes
            for bi in range(0, len(rawNo)):
                priceCents = self.safe_number(rawNo[bi], 0)
                bids.append([priceCents / 100, self.safe_number(rawNo[bi], 1)])
            for ai in range(0, len(rawYes)):
                priceCents = self.safe_number(rawYes[ai], 0)
                asks.append([(100 - priceCents) / 100, self.safe_number(rawYes[ai], 1)])
        else:
            # YES perspective: YES bids from rawYes, YES asks invert rawNo
            for bi in range(0, len(rawYes)):
                priceCents = self.safe_number(rawYes[bi], 0)
                bids.append([priceCents / 100, self.safe_number(rawYes[bi], 1)])
            for ai in range(0, len(rawNo)):
                priceCents = self.safe_number(rawNo[ai], 0)
                asks.append([(100 - priceCents) / 100, self.safe_number(rawNo[ai], 1)])
        return self.sorted_orders(outcome, timestamp, bids, asks)

    def sorted_orders(self, symbol: Str, timestamp: Int, bids: List[Any], asks: List[Any]) -> OrderBook:
        """
 Sorts bids descending and asks ascending, then returns a CCXT-shaped OrderBook object.
 @param symbol
 @param timestamp
 @param bids
 @param asks
        """
        # Sort bids descending, asks ascending, match CCXT OrderBook shape
        bids = self.sort_by(bids, 0, True)
        asks = self.sort_by(asks, 0)
        return {
            'symbol': symbol,
            'bids': bids,
            'asks': asks,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'nonce': None,
        }

    async def fetch_ohlcv(self, outcome: Str, timeframe='1m', since: Int = None, limit: Int = None, params: dict = {}) -> List[list]:
        """
 Fetches OHLCV candlesticks for a single Kalshi outcome from the candlesticks endpoint.
 @param outcome
 @param timeframe
 @param since
 @param limit
 @param params

        https://trading-api.readme.io/reference/getcandlesticks

        """
        await self.load_markets()
        outcomeObj = self.outcome(outcome)
        ticker = self.safe_string(outcomeObj['info'], 'ticker')
        seriesTicker = self.safe_string(outcomeObj['info'], 'seriesTicker', ticker)
        periodMin = self.safe_integer(self.timeframes, timeframe, 1)
        request: dict = {
            'series_ticker': seriesTicker,
            'ticker': ticker,
            'period_interval': periodMin,
        }
        if since is not None:
            request['start_ts'] = self.parse_to_int(since / 1000)
        if limit is not None and since is not None:
            tf = self.parse_timeframe(timeframe)
            end = (since / 1000) + limit * tf
            now = self.seconds()
            request['end_ts'] = end < end if now else now
        response = await self.kalshiPublicGetSeriesSeriesTickerMarketsTickerCandlesticks(
            self.extend(request, params)
        )
        candles = self.safe_list(response, 'candlesticks', [])
        return self.parse_ohlcvs(candles, outcomeObj, timeframe, since, limit)

    def parse_ohlcv(self, ohlcv: dict, market: Market = None) -> list:
        """
 Parses a single Kalshi candlestick object into a CCXT OHLCV tuple, converting cent prices to decimals.
 @param ohlcv
 @param market
        """
        # Kalshi candlestick prices are in cents → divide by 100
        ts = self.safe_integer(ohlcv, 'end_period_ts')
        open = self.safe_number(ohlcv, 'open')
        high = self.safe_number(ohlcv, 'high')
        low = self.safe_number(ohlcv, 'low')
        close = self.safe_number(ohlcv, 'close')
        vol = self.safe_number(ohlcv, 'volume')
        return [
            ts is not ts * 1000 if None else None,
            open is not open / 100 if None else None,
            high is not high / 100 if None else None,
            low is not low / 100 if None else None,
            close is not close / 100 if None else None,
            vol,
        ]

    async def fetch_trades(self, outcome: Str, since: Int = None, limit: Int = None, params: dict = {}) -> List[Trade]:
        """
 Fetches public trade history for a single Kalshi market ticker.
 @param outcome
 @param since
 @param limit
 @param params

        https://trading-api.readme.io/reference/getmarkettrades

        """
        await self.load_markets()
        outcomeObj = self.outcome(outcome)
        ticker = self.safe_string(outcomeObj['info'], 'ticker')
        request: dict = {'ticker': ticker}
        if limit is not None:
            request['limit'] = limit
        response = await self.kalshiPublicGetMarketsTickerTrades(self.extend(request, params))
        trades = self.safe_list(response, 'trades', [])
        return self.parse_trades(trades, outcomeObj, since, limit)

    def parse_trade(self, trade: dict, market: Market = None) -> Trade:
        """
 Parses a raw Kalshi trade object into a unified CCXT Trade object.
 @param trade
 @param market
        """
        id = self.safe_string(trade, 'trade_id')
        ts = self.parse8601(self.safe_string(trade, 'created_time'))
        priceCents = self.safe_number(trade, 'yes_price')
        price = priceCents is not priceCents / 100 if None else None
        amount = self.safe_number(trade, 'count')
        rawSide = self.safe_string_lower(trade, 'taker_side')
        side: str | None
        if rawSide == 'yes':
            side = 'buy'
        elif rawSide == 'no':
            side = 'sell'
        return self.safe_trade({
            'id': id,
            'info': trade,
            'timestamp': ts,
            'datetime': self.iso8601(ts),
            'symbol': self.safe_symbol(None, market),
            'order': None,
            'type': None,
            'side': side,
            'takerOrMaker': 'taker',
            'price': price,
            'amount': amount,
            'cost': price * amount if (price is not None and amount is not None) else None,
            'fee': None,
        }, market)

    async def fetch_balance(self, params: dict = {}) -> Balances:
        """
 Fetches the authenticated user's USD portfolio balance from Kalshi.
 @param params

        https://trading-api.readme.io/reference/getbalance

        """
        response = await self.kalshiPrivateGetPortfolioBalance(params)
        return self.parse_balance(response)

    def parse_balance(self, response: dict) -> Balances:
        """
 Parses a Kalshi balance response(cents) into a CCXT Balances object with a USD entry.
 @param response
        """
        # Kalshi balance in cents → divide by 100
        result: dict = {'info': response}
        balanceCents = self.safe_number(response, 'balance')
        total = balanceCents is not balanceCents / 100 if None else None
        result['USD'] = {'free': total, 'used': 0, 'total': total}
        return result

    async def fetch_positions(self, outcomes: List[Str], params: dict = {}) -> List[Position]:
        """
 Fetches open market positions for the authenticated Kalshi user.
 @param outcomes
 @param params

        https://trading-api.readme.io/reference/getportfoliopositions

        """
        response = await self.kalshiPrivateGetPortfolioPositions(params)
        positions = self.safe_list(response, 'market_positions', [])
        return self.parse_positions(positions, outcomes)

    def parse_position(self, position: dict, market: Market = None) -> Position:
        """
 Parses a raw Kalshi portfolio position into a unified CCXT Position object.
 @param position
 @param market
        """
        ticker = self.safe_string(position, 'ticker')
        outcomeObj = self.safe_outcome(ticker, market)
        yesContracts = self.safe_number(position, 'position')  # positive = long YES
        positionSide: str | None
        if yesContracts is not None:
            positionSide = yesContracts >= 'long' if 0 else 'short'
        return {
            'id': None,
            'symbol': self.safe_string(outcomeObj, 'symbol', ticker),
            'timestamp': None,
            'datetime': None,
            'contracts': yesContracts is not abs(yesContracts) if None else None,
            'contractSize': 1,
            'side': positionSide,
            'notional': None,
            'leverage': 1,
            'unrealizedPnl': None,
            'realizedPnl': None,
            'collateral': None,
            'entryPrice': None,
            'markPrice': None,
            'liquidationPrice': None,
            'hedged': False,
            'maintenanceMargin': None,
            'maintenanceMarginPercentage': None,
            'initialMargin': None,
            'initialMarginPercentage': None,
            'marginRatio': None,
            'marginMode': 'cross',
            'marginType': 'cross',
            'percentage': None,
            'info': position,
        }

    async def fetch_open_orders(self, outcome: Str = None, since: Int = None, limit: Int = None, params: dict = {}) -> List[Order]:
        """
 Fetches resting(open) orders for the authenticated Kalshi user, optionally filtered by ticker.
 @param outcome
 @param since
 @param limit
 @param params

        https://trading-api.readme.io/reference/getorders

        """
        request: dict = {'status': 'resting'}
        outcomeObj: Any = None
        if outcome is not None:
            outcomeObj = self.outcome(outcome)
            request['ticker'] = self.safe_string(outcomeObj['info'], 'ticker')
        response = await self.kalshiPrivateGetPortfolioOrders(self.extend(request, params))
        orders = self.safe_list(response, 'orders', [])
        return self.parse_orders(orders, outcomeObj, since, limit)

    async def fetch_order(self, id: Str, symbol: Str = None, params: dict = {}) -> Order:
        """
 Fetches a single order by ID from the Kalshi portfolio endpoint.
 @param id
 @param symbol
 @param params

        https://trading-api.readme.io/reference/getorder

        """
        response = await self.kalshiPrivateGetPortfolioOrdersOrderId(self.extend({'order_id': id}, params))
        return self.parse_order(self.safe_value(response, 'order', response))

    def parse_order(self, order: dict, market: Market = None) -> Order:
        """
 Parses a raw Kalshi order object into a unified CCXT Order object.
 @param order
 @param market
        """
        id = self.safe_string(order, 'order_id')
        ticker = self.safe_string(order, 'ticker')
        mkt = self.safe_outcome(ticker, market)
        status = self.parse_order_status(self.safe_string(order, 'status'))
        side = self.safe_string(order, 'action') == 'buy' if 'buy' else 'sell'
        priceCents = self.safe_number(order, 'no_price', self.safe_number(order, 'yes_price'))
        price = priceCents is not priceCents / 100 if None else None
        amount = self.safe_number(order, 'count')
        filled = self.safe_number(order, 'filled_count', 0)
        remaining = amount - filled if (amount is not None and filled is not None) else None
        ts = self.parse8601(self.safe_string(order, 'created_time'))
        return self.safe_order({
            'id': id,
            'clientOrderId': self.safe_string(order, 'client_order_id'),
            'info': order,
            'timestamp': ts,
            'datetime': self.iso8601(ts),
            'lastTradeTimestamp': None,
            'status': status,
            'symbol': mkt['symbol'],
            'type': self.safe_string_lower(order, 'type', 'limit'),
            'timeInForce': 'GTC',
            'postOnly': None,
            'side': side,
            'price': price,
            'stopPrice': None,
            'triggerPrice': None,
            'average': None,
            'amount': amount,
            'cost': None,
            'filled': filled,
            'remaining': remaining,
            'fee': None,
            'trades': [],
        }, mkt)

    def parse_order_status(self, status: Str) -> Str:
        """
 Maps a Kalshi order status string to the CCXT unified status vocabulary.
 @param status
        """
        statuses: dict = {
            'resting': 'open',
            'executed': 'closed',
            'canceled': 'canceled',
            'pending': 'open',
        }
        return self.safe_string(statuses, status, status)

    async def create_order(self, outcome: Str, type: Str, side: Str, amount: Num, price: Num = None, params: dict = {}) -> Order:
        """
 Places a limit or market order on Kalshi for the given outcome token.
 @param outcome
 @param type
 @param side
 @param amount
 @param price
 @param params

        https://trading-api.readme.io/reference/createorder

        """
        await self.load_markets()
        outcomeObj = self.outcome(outcome)
        ticker = self.safe_string(outcomeObj['info'], 'ticker')
        outcomeLabel = outcomeObj['label']
        priceCents = price is not self.parse_to_int(price * 100 + 0.5) if None else None
        request: dict = {
            'action': side == 'buy' if 'buy' else 'sell',
            'count': amount,
            'side': outcomeLabel == 'no' if 'NO' else 'yes',
            'ticker': ticker,
            'type': type,
        }
        if priceCents is not None:
            request[outcomeLabel == 'no_price' if 'NO' else 'yes_price'] = priceCents
        response = await self.kalshiPrivatePostPortfolioOrders(self.extend(request, params))
        return self.parse_order(self.safe_value(response, 'order', response), outcomeObj)

    async def cancel_order(self, id: Str, symbol: Str = None, params: dict = {}) -> Order:
        """
 Cancels a single open order by ID on Kalshi.
 @param id
 @param symbol
 @param params

        https://trading-api.readme.io/reference/cancelorder

        """
        response = await self.kalshiPrivateDeletePortfolioOrdersOrderId(self.extend({'order_id': id}, params))
        return self.parse_order(self.safe_value(response, 'order', response))

    async def cancel_all_orders(self, outcome: Str = None, params: dict = {}) -> List[Order]:
        """
 Cancels all open orders on Kalshi, optionally scoped to one outcome ticker.
 @param outcome
 @param params

        https://trading-api.readme.io/reference/cancelorders

        """
        request: dict = {}
        if outcome is not None:
            await self.load_markets()
            outcomeObj = self.outcome(outcome)
            request['ticker'] = self.safe_string(outcomeObj['info'], 'ticker')
        response = await self.kalshiPrivateDeletePortfolioOrders(self.extend(request, params))
        return self.parse_orders(self.safe_list(response, 'orders', []))

    async def fetch_events(self, queries: List[str] = [], params: dict = {}) -> Any:
        """
 Fetches Kalshi events via cursor-paginated /events, filters client-side by query strings,
 then fetches full event details with nested markets in parallel and caches in self.events.
 @param queries
 @param params

        https://trading-api.readme.io/reference/getevents

        """
        status = self.safe_string(params, 'status', self.safe_string(self.options, 'defaultEventStatus', 'open'))
        pageLimit = self.safe_integer(params, 'limit', 200)
        maxPages = self.safe_integer(params, 'maxPages', 5)
        rest = self.omit(params, ['status', 'limit', 'maxPages'])
        if not self.events:
            self.events = {}
        if not self.markets:
            self.markets = {}
        lowerQueries: List[str] = []
        for qi in range(0, len(queries)):
            lowerQueries.append((queries[qi]).lower())
        # Phase 1: sequential cursor scan(lightweight — no nested markets) to collect matching tickers
        matchedTickers: str[] = []
        cursor: str | None = None
        page = 0
        while(page < maxPages):
            request: dict = {'status': status, 'limit': pageLimit}
            if cursor:
                request['cursor'] = cursor
            response = await self.kalshiPublicGetEvents(self.extend(request, rest))
            rawEvents = self.safe_list(response, 'events', [])
            cursor = self.safe_string(response, 'cursor')
            for rei in range(0, len(rawEvents)):
                rawEvent = rawEvents[rei]
                ticker = (self.safe_string(rawEvent, 'event_ticker') or '')
                title = (self.safe_string(rawEvent, 'title') or '').lower()
                matches = (len(lowerQueries) == 0)
                for li in range(0, len(lowerQueries)):
                    if ticker.lower().find(lowerQueries[li]) != -1 or title.find(lowerQueries[li]) != -1:
                        matches = True
                        break
                if matches and ticker:
                    matchedTickers.append(ticker)
            page++
            if not cursor or len(rawEvents) < pageLimit:
                break
        # Phase 2: fetch full event details(with nested markets) for all matched tickers in parallel
        detailPromises: Any[] = []
        for ti in range(0, len(matchedTickers)):
            detailPromises.append(self.kalshiPublicGetEventsEventTicker({'event_ticker': matchedTickers[ti], 'with_nested_markets': True}))
        detailResponses = await asyncio.gather(*detailPromises)
        result: dict = {}
        for di in range(0, len(detailResponses)):
            detail = detailResponses[di]
            fullEvent = self.safe_value(detail, 'event', detail)
            parsedEvent = self.parse_event(fullEvent)
            eventTitle = self.safe_string(fullEvent, 'title')
            eventKey = self.shorten_slug(eventTitle) if eventTitle else None
            if eventKey:
                (self.events)[eventKey] = parsedEvent
                result[eventKey] = parsedEvent
                parsedMarkets = (parsedEvent['markets'] or [])
                for mi in range(0, len(parsedMarkets)):
                    m = parsedMarkets[mi]
                    self.markets[m['symbol']] = m
        return list(result.values())

    def parse_event(self, rawEvent: dict) -> PredictionEvent:
        """
 Parses a raw Kalshi event object(with nested markets) into the unified CCXT event shape.
 @param rawEvent
        """
        # {
        #         "available_on_brokers": True,
        #         "category": "Politics",
        #         "collateral_return_type": "",
        #         "event_ticker": "KXBALANCE-29",
        #         "last_updated_ts": "0001-01-01T00:00:00Z",
        #         "markets": [
        #             {
        #                 "can_close_early": True,
        #                 "close_time": "2029-07-01T14:00:00Z",
        #                 "created_time": "0001-01-01T00:00:00Z",
        #                 "early_close_condition": "This market will close and expire early if the event occurs.",
        #                 "event_ticker": "KXBALANCE-29",
        #                 "expected_expiration_time": "2029-07-01T14:00:00Z",
        #                 "expiration_time": "2029-07-01T14:00:00Z",
        #                 "expiration_value": "",
        #                 "fractional_trading_enabled": False,
        #                 "last_price_dollars": "0.1000",
        #                 "latest_expiration_time": "2029-07-01T14:00:00Z",
        #                 "liquidity_dollars": "0.0000",
        #                 "market_type": "binary",
        #                 "no_ask_dollars": "0.9000",
        #                 "no_bid_dollars": "0.8900",
        #                 "no_sub_title": "During Trump's term",
        #                 "notional_value_dollars": "1.0000",
        #                 "open_interest_fp": "16268.00",
        #                 "open_time": "2025-01-03T15:00:00Z",
        #                 "previous_price_dollars": "0.0000",
        #                 "previous_yes_ask_dollars": "0.0000",
        #                 "previous_yes_bid_dollars": "0.0000",
        #                 "price_level_structure": "linear_cent",
        #                 "price_ranges": [
        #                     {
        #                         "end": "1.0000",
        #                         "start": "0.0000",
        #                         "step": "0.0100"
        #                     }
        #                 ],
        #                 "response_price_units": "usd_cent",
        #                 "result": "",
        #                 "rules_primary": "If there is not a budget deficit for any of fiscal years 2025, 2026, 2027, or 2028, then the market resolves to Yes.",
        #                 "rules_secondary": "",
        #                 "settlement_timer_seconds": "1800",
        #                 "status": "active",
        #                 "subtitle": "",
        #                 "tick_size": "1",
        #                 "ticker": "KXBALANCE-29",
        #                 "title": "Will Trump balance the budget?",
        #                 "updated_time": "0001-01-01T00:00:00Z",
        #                 "volume_24h_fp": "28.00",
        #                 "volume_fp": "40111.00",
        #                 "yes_ask_dollars": "0.1100",
        #                 "yes_ask_size_fp": "",
        #                 "yes_bid_dollars": "0.1000",
        #                 "yes_bid_size_fp": "",
        #                 "yes_sub_title": "During Trump's term"
        #             }
        #         ],
        #         "mutually_exclusive": False,
        #         "series_ticker": "KXBALANCE",
        #         "strike_period": "",
        #         "sub_title": "During Trump's term",
        #         "title": "Will Trump balance the budget?"
        # }
        rawMarkets = self.safe_list(rawEvent, 'markets', [])
        marketsList: List[Any] = []
        for(rawMarket of rawMarkets) {
            parsed = self.parse_market(rawMarket)
            marketsList.append(parsed)
        ticker = self.safe_string(rawEvent, 'event_ticker')
        title = self.safe_string(rawEvent, 'title')
        return self.extend({
            'id': ticker,
            'slug': ticker,
            'symbol': self.shorten_slug(title) if title else None,
            'title': title,
            'markets': marketsList,
            'url': self.safe_string(rawEvent, 'url'),
            'image': self.safe_string(rawEvent, 'image_url'),
            'created': self.parse8601(self.safe_string(rawEvent, 'created_date_iso')),
            'createdDatetime': self.safe_string(rawEvent, 'created_date_iso'),
            'end': self.parse8601(self.safe_string(rawEvent, 'end_date_iso')),
            'endDatetime': self.safe_string(rawEvent, 'end_date_iso'),
            'category': self.safe_string(rawEvent, 'category'),
            'lastUpdatedAt': self.parse8601(self.safe_string(rawEvent, 'last_updated_date_iso')),
            'lastUpdatedAtDatetime': self.safe_string(rawEvent, 'last_updated_date_iso'),
            'resolutionSource': self.safe_string(rawEvent, 'resolution_source'),
            'resolved': self.safe_bool(rawEvent, 'resolved'),
            'info': rawEvent,
        })

    def sign(self, path: Str, api: Any = 'kalshi', method='GET', params: dict = {}, headers: dict = None, body: dict = None):
        """
 Builds the request URL and attaches RSA-PSS SHA-256 authentication headers for private endpoints.
 @param path
 @param api
 @param method
 @param params
 @param headers
 @param body
        """
        apiGroup: str = api if isinstance(api, str) else api[0]
        access: str = 'public' if isinstance(api, str) else api[1]
        baseUrls = self.urls['api']
        baseUrl = self.safe_string(baseUrls, apiGroup, baseUrls['kalshi'])
        url = baseUrl + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_paramspath)
        querystring = self.urlencode(query)
        if method == 'GET' and querystring:
            url += '?' + querystring
        headers = self.extend({
            'Accept': 'application/json',
            'Content-Type': 'application/json',
        }, headers or {})
        if access == 'private':
            self.check_required_credentials()
            timestamp = str(self.milliseconds())
            # Signing payload: {timestamp}{METHOD}/{path_without_base}
            pathForSigning = '/' + path
            payload = timestamp + method + pathForSigning
            # RSA-PSS SHA-256 signature with the private key PEM
            signature = self.rsa(payload, self.privateKey.replace(/\\n/g, '\n'), 'SHA256')
            headers = self.extend(headers, {
                'KALSHI-ACCESS-KEY': self.apiKey,
                'KALSHI-ACCESS-SIGNATURE': signature,
                'KALSHI-ACCESS-TIMESTAMP': timestamp,
            })
            if method != 'GET' and querystring:
                body = query
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
