# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.polymarket import ImplicitAPI
import asyncio
import math
from ccxt.base.types import Any, Balances, Int, Market, Num, Order, OrderBook, Position, Str, Strings, Ticker, Tickers, Trade
from typing import List
from ccxt.base.errors import ArgumentsRequired


class polymarket(Exchange, ImplicitAPI):

    def describe(self):
        return self.deep_extend(super(polymarket, self).describe(), {
            'id': 'polymarket',
            'name': 'Polymarket',
            'countries': ['US'],
            'rateLimit': 100,
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'cancelAllOrders': True,
                'cancelOrder': True,
                'createOrder': True,
                'fetchBalance': True,
                'fetchCurrencies': False,
                'fetchDeposits': False,
                'fetchEvents': True,        # Custom: fetch Polymarket events
                'fetchLedger': False,
                'fetchMarkets': True,       # Each outcome token = one market
                'fetchMyTrades': False,
                'fetchOHLCV': True,
                'fetchOpenOrders': True,
                'fetchOrder': True,
                'fetchOrderBook': True,
                'fetchPositions': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchTrades': True,
                'fetchWithdrawals': False,
                'prediction': True,         # Prediction market support
            },
            'timeframes': {
                '1m': '1',
                '5m': '5',
                '1h': '60',
                '6h': '360',
                '1d': '1440',
            },
            'urls': {
                'logo': 'https://polymarket.com/favicon.ico',
                'api': {
                    'gamma': 'https://gamma-api.polymarket.com',
                    'clob': 'https://clob.polymarket.com',
                    'data': 'https://data-api.polymarket.com',
                },
                'www': 'https://polymarket.com',
                'doc': ['https://docs.polymarket.com'],
                'fees': 'https://docs.polymarket.com/#fees',
            },
            'api': {
                'gamma': {
                    'public': {
                        'get': {
                            'events': 1,
                            'events/{id}': 1,
                            'events/slug/{slug}': 1,
                            'markets': 1,
                            'markets/{id}': 1,
                            'public-search': 1,
                        },
                    },
                },
                'clob': {
                    'public': {
                        'get': {
                            'book': 1,
                            'prices-history': 1,
                            'data/trades': 1,
                            'price': 1,
                            'midpoint': 1,
                            'spread': 1,
                        },
                    },
                    'private': {
                        'get': {
                            'data/orders': 1,
                            'data/order/{id}': 1,
                        },
                        'post': {
                            'order': 1,
                        },
                        'delete': {
                            'order': 1,
                            'orders': 1,
                        },
                    },
                },
                'data': {
                    'private': {
                        'get': {
                            'positions': 1,
                            'trades': 1,
                            'value': 1,
                        },
                    },
                },
            },
            'requiredCredentials': {
                'apiKey': True,   # POLY_API_KEY
                'secret': True,   # POLY_API_SECRET
                'password': True,   # POLY_PASSPHRASE
                'walletAddress': True,   # Ethereum wallet address
            },
            'fees': {
                'trading': {
                    'tierBased': False,
                    'percentage': True,
                    'maker': 0.0,
                    'taker': 0.0,
                },
            },
            'options': {
                'defaultFetchEventsLimit': 100,
                'maxFetchEventsLimit': 500,
                'defaultEventStatus': 'active',  # 'active' | 'closed' | 'all'
            },
        })

    async def fetch_markets(self, params: dict = {}) -> List[Market]:
        queries = self.safe_list(params, 'queries', [])
        rest0 = self.omit(params, ['queries'])
        pageSize = 0
        flatMarkets: List[Market] = []
        eventsDict: dict = {}
        if queries and len(queries) > 0:
            pageSize = self.safe_integer(rest0, 'limit', 50)
            searchRest = self.omit(rest0, ['limit'])
            seen: dict = {}
            rawEvents: Any[] = []
            for qi in range(0, len(queries)):
                q = queries[qi]
                baseRequest1: dict = {'q': q, 'limit_per_type': pageSize, 'events_status': 'active'}
                firstRequest: dict = {'page': 1}
                firstRequest = self.extend(firstRequest, baseRequest1, searchRest)
                first = await self.gammaPublicGetPublicSearch(firstRequest)
                firstEvents = self.safe_list(first, 'events', [])
                pagination = self.safe_value(first, 'pagination', {})
                totalResults = self.safe_integer(pagination, 'totalResults', len(firstEvents))
                totalPages = int(math.ceil(totalResults / pageSize))
                remaining: number[] = []
                for p in range(2, totalPages):
                    remaining.append(p)
                restPromises: Any[] = []
                for pi in range(0, len(remaining)):
                    pageRequest: dict = {'page': remaining[pi]}
                    pageRequest = self.extend(pageRequest, baseRequest1, searchRest)
                    restPromises.append(self.gammaPublicGetPublicSearch(pageRequest))
                restResponses = await asyncio.gather(*restPromises)
                allEvents: Any[] = []
                for fi in range(0, len(firstEvents)):
                    allEvents.append(firstEvents[fi])
                for ri in range(0, len(restResponses)):
                    pageEvents = self.safe_list(restResponses[ri], 'events', [])
                    for ei in range(0, len(pageEvents)):
                        allEvents.append(pageEvents[ei])
                for ei in range(0, len(allEvents)):
                    rawEvent = allEvents[ei]
                    eventId = self.safe_string(rawEvent, 'id')
                    if eventId and not seen[eventId]:
                        seen[eventId] = True
                        rawEvents.append(rawEvent)
            for rei in range(0, len(rawEvents)):
                rawEvent = rawEvents[rei]
                ccxtMarkets = self.parse_event_to_markets(rawEvent)
                for mi in range(0, len(ccxtMarkets)):
                    flatMarkets.append(ccxtMarkets[mi])
                parsedEvent = self.parse_event(rawEvent)
                eventSlug = self.safe_string(rawEvent, 'slug')
                if eventSlug:
                    eventKey = self.shorten_slugeventSlug
                    eventsDict[eventKey] = parsedEvent
            self.events = eventsDict
            return flatMarkets
        pageSize = self.safe_integer(self.options, 'maxFetchEventsLimit', 500)
        maxPages = 20
        status = self.safe_string(rest0, 'status', self.safe_string(self.options, 'defaultEventStatus', 'active'))
        rest = self.omit(rest0, ['status'])
        baseRequest: dict = {'limit': pageSize, 'order': 'volume24hr', 'ascending': False}
        baseRequest = self.extend(baseRequest, rest)
        if status == 'active':
            baseRequest['active'] = True
        elif status == 'closed':
            baseRequest['closed'] = True
        # Fetch page 1 first; if full, fire remaining pages in parallel
        firstPageRequest: dict = {'offset': 0}
        firstPageRequest = self.extend(firstPageRequest, baseRequest)
        firstPageResponse = await self.gammaPublicGetEvents(firstPageRequest)
        firstPage = (firstPageResponse or [])
        allRawEvents: Any[] = []
        for fi in range(0, len(firstPage)):
            allRawEvents.append(firstPage[fi])
        if len(firstPage) >= pageSize:
            offsets: number[] = []
            for p in range(1, maxPages):
                offsets.append(p * pageSize)
            restPromises2: Any[] = []
            for oi in range(0, len(offsets)):
                pageRequest: dict = {'offset': offsets[oi]}
                pageRequest = self.extend(pageRequest, baseRequest)
                restPromises2.append(self.gammaPublicGetEvents(pageRequest))
            restPages = await asyncio.gather(*restPromises2)
            for ri2 in range(0, len(restPages)):
                page = (restPages[ri2] or [])
                for pi2 in range(0, len(page)):
                    allRawEvents.append(page[pi2])
        for rei in range(0, len(allRawEvents)):
            rawEvent = allRawEvents[rei]
            ccxtMarkets = self.parse_event_to_markets(rawEvent)
            for mi in range(0, len(ccxtMarkets)):
                flatMarkets.append(ccxtMarkets[mi])
            parsedEvent = self.parse_event(rawEvent)
            eventSlug = self.safe_string(rawEvent, 'slug')
            if eventSlug:
                eventKey = self.shorten_slugeventSlug
                eventsDict[eventKey] = parsedEvent
        self.events = eventsDict
        return flatMarkets

    def parse_event_to_markets(self, event: dict) -> List[Market]:
        eventSlug = self.safe_string(event, 'slug', self.safe_string(event, 'id'))
        rawMarkets = self.safe_list(event, 'markets', [])
        result: List[Market] = []
        #
        # {
        #    "id":"604489",
        #    "question":"Will Trump visit China by October 31?",
        #    "conditionId":"0x3d69cc559693ee46ba58da16e43c4e75b8da67b99c2e9a9d2f72bb0222d0f137",
        #    "slug":"will-trump-visit-china-by-october-31",
        #    "resolutionSource":"",
        #    "endDate":"2025-10-31T00:00:00Z",
        #    "startDate":"2025-09-19T21:22:54.912576Z",
        #    "image":"https://polymarket-upload.s3.us-east-2.amazonaws.com/will-trump-visit-china-by-october-31-ujqWMja0Uizt.png",
        #    "icon":"https://polymarket-upload.s3.us-east-2.amazonaws.com/will-trump-visit-china-by-october-31-ujqWMja0Uizt.png",
        #    "description":"If U.S. President Donald Trump visits China by October 31, 2025, 11:59 PM ET, self market will resolve to \\""Yes\\"". Otherwise, self market will resolve to \\""No\\"".\\n\\nFor the purpose of self market, a \\""visit\\"" is defined physically entering the terrestrial or maritime territory of the listed country. Whether or not Trump enters the country's airspace during the timeframe of self market will have no bearing on a positive resolution.\\n\\nThe primary resolution source for self information will be official information from government of the United States of America, official information from Trump or released by his verified social media accounts(e.g. https://twitter.com/POTUS), however, a consensus of credible reporting will also be used.",
        #    "outcomes":"[\\""Yes\\"", \\""No\\""]",
        #    "outcomePrices":"[\\"0\\", \\"1\\"]",
        #    "volume":"549414.493468",
        #    "active":true,
        #    "closed":true,
        #    "marketMakerAddress":"",
        #    "createdAt":"2025-09-19T19:32:28.841694Z",
        #    "updatedAt":"2026-03-09T22:44:28.896812Z",
        #    "closedTime":"2025-11-01 06:28:08+00",
        #    "new":false,
        #    "featured":false,
        #    "submitted_by":"0x91430CaD2d3975766499717fA0D66A78D814E5c5",
        #    "archived":false,
        #    "resolvedBy":"0x65070BE91477460D8A7AeEb94ef92fe056C2f2A7",
        #    "restricted":true,
        #    "groupItemTitle":"October 31, 2025",
        #    "groupItemThreshold":"0",
        #    "questionID":"0x2dd49c70f01a5e7c687a9820d606ff0d85fb50199735928d52d98b3a57586969",
        #    "umaEndDate":"2025-11-01T06:28:08Z",
        #    "enableOrderBook":true,
        #    "orderPriceMinTickSize":"0.001",
        #    "orderMinSize":"5",
        #    "umaResolutionStatus":"resolved",
        #    "volumeNum":"549414.493468",
        #    "endDateIso":"2025-10-31",
        #    "startDateIso":"2025-09-19",
        #    "hasReviewedDates":true,
        #    "volume1wk":"121949.66579699998",
        #    "volume1mo":"535231.3545640002",
        #    "volume1yr":"549414.4934680002",
        #    "clobTokenIds":"[\\"45601394554497090173642354630373884477724604907691447337031201817815960365378\\", \\"102652665954921241745169157447280060113772926009745753029489061659654862632571\\"]",
        #    "umaBond":"500",
        #    "umaReward":"5",
        #    "volume1wkClob":"121949.66579699998",
        #    "volume1moClob":"535231.3545640002",
        #    "volume1yrClob":"549414.4934680002",
        #    "volumeClob":"549414.493468",
        #    "customLiveness":"0",
        #    "acceptingOrders":false,
        #    "negRisk":false,
        #    "negRiskRequestID":"",
        #    "ready":false,
        #    "funded":false,
        #    "acceptingOrdersTimestamp":"2025-09-19T21:22:32Z",
        #    "cyom":false,
        #    "pagerDutyNotificationEnabled":false,
        #    "approved":true,
        #    "rewardsMinSize":"100",
        #    "rewardsMaxSpread":"3.5",
        #    "spread":"0.001",
        #    "automaticallyResolved":true,
        #    "oneDayPriceChange":"-0.0005",
        #    "oneWeekPriceChange":"-0.007",
        #    "oneMonthPriceChange":"-0.011",
        #    "lastTradePrice":"1",
        #    "bestAsk":"0.001",
        #    "automaticallyActive":true,
        #    "clearBookOnStart":true,
        #    "seriesColor":"",
        #    "showGmpSeries":false,
        #    "showGmpOutcome":false,
        #    "manualActivation":false,
        #    "negRiskOther":false,
        #    "umaResolutionStatuses":"[\\""proposed\\""]",
        #    "pendingDeployment":false,
        #    "deploying":false,
        #    "deployingTimestamp":"2025-09-19T21:22:01.979023Z",
        #    "rfqEnabled":false,
        #    "holdingRewardsEnabled":false,
        #    "feesEnabled":false,
        #    "requiresTranslation":false,
        #    "feeType":null
        # }
        #
        for mi in range(0, len(rawMarkets)):
            market = rawMarkets[mi]
            conditionId = self.safe_string(market, 'conditionId')
            marketId = self.safe_string(market, 'id')
            marketSlug = self.safe_string(market, 'slug', conditionId)
            active = self.safe_bool(market, 'active', False)
            closed = self.safe_bool(market, 'closed', False)
            tickSize = self.safe_number(market, 'minimumTickSize', 0.01)
            endDate = self.safe_string(market, 'endDate', self.safe_string(market, 'end_date_iso'))
            # Gamma API returns these arrays-encoded strings
            outcomeLabels: str[] = []
            clobTokenIds: str[] = []
            outcomePrices: str[] = []
            parsedOutcomes = self.parse_json(self.safe_string(market, 'outcomes', '[]'))
            parsedTokenIds = self.parse_json(self.safe_string(market, 'clobTokenIds', '[]'))
            parsedPrices = self.parse_json(self.safe_string(market, 'outcomePrices', '[]'))
            if parsedOutcomes and (len(parsedOutcomes)) is not None:
                outcomeLabels = parsedOutcomes
            if parsedTokenIds and (len(parsedTokenIds)) is not None:
                clobTokenIds = parsedTokenIds
            if parsedPrices and (len(parsedPrices)) is not None:
                outcomePrices = parsedPrices
            if len(outcomeLabels) == 0 or len(clobTokenIds) == 0:
                continue
            # Market symbol(no outcome suffix)
            marketSymbol = self.slug_to_market_symbol(eventSlug, marketSlug)
            # Build outcomes array
            outcomes: Any[] = []
            for oi in range(0, len(outcomeLabels)):
                outcomeLabel = outcomeLabels[oi]
                clobTokenId = clobTokenIds[oi]
                outcomePrice = self.safe_number(outcomePrices, oi)
                if not clobTokenId:
                    continue
                outcomes.append({
                    'id': clobTokenId,
                    'symbol': marketSymbol + ':' + outcomeLabel.upper(),
                    'marketSymbol': marketSymbol,
                    'label': outcomeLabel,
                    'price': outcomePrice,
                    'active': active and not closed,
                    'info': market,
                })
            result.append({
                'id': conditionId,
                'symbol': marketSymbol,
                'base': 'USDC',
                'quote': 'USDC',
                'settle': None,
                'baseId': conditionId or marketId,
                'quoteId': 'USDC',
                'settleId': None,
                'type': 'prediction',
                'spot': False,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'prediction': True,
                'active': active and not closed,
                'contract': False,
                'linear': None,
                'inverse': None,
                'contractSize': None,
                'expiry': self.parse8601(endDate) if endDate else None,
                'expiryDatetime': endDate,
                'strike': None,
                'optionType': None,
                'taker': 0.0,
                'maker': 0.0,
                'percentage': True,
                'tierBased': False,
                'feeSide': 'get',
                'precision': {
                    'amount': tickSize,
                    'price': tickSize,
                },
                'limits': {
                    'leverage': {'min': 1, 'max': 1},
                    'amount': {'min': 1, 'max': None},
                    'price': {'min': 0.01, 'max': 0.99},
                    'cost': {'min': None, 'max': None},
                },
                'outcomes': outcomes,
                'info': market,
                'created': None,
            })
        return result

    async def fetch_ticker(self, outcome: str, params: dict = {}) -> Ticker:
        """
 Fetches the current mid-price and best bid/ask for a single outcome token.
 @param outcome
 @param params

        https://docs.polymarket.com/api-reference/data/get-midpoint-price
        https://docs.polymarket.com/api-reference/market-data/get-order-book

        """
        await self.load_markets()
        outcomeObj = self.outcome(outcome)
        tokenId = outcomeObj['id']
        # Sequential to avoid asyncio.gather(*not in lib scope)
        midpointResponse = await self.clobPublicGetMidpoint({'token_id': tokenId})
        bookResponse = await self.clobPublicGetBook({'token_id': tokenId})
        return self.parse_ticker(
            {'midpoint': midpointResponse, 'book': bookResponse},
            outcomeObj
        )

    async def fetch_tickers(self, outcomes: List[Str], params: dict = {}) -> Tickers:
        """
 Fetches tickers for multiple outcome tokens sequentially.
 @param outcomes
 @param params

        https://docs.polymarket.com/api-reference/data/get-midpoint-price

        """
        await self.load_markets()
        targets: List[str] = (outcomes) if outcomes else list(self.outcomes or {}.keys())
        result: Tickers = {}
        for(outcomeSymbol of targets) {
            ticker = await self.fetch_ticker(outcomeSymbol, params)
            result[outcomeSymbol] = ticker
        return result

    def parse_ticker(self, ticker: dict, market: Market = None) -> Ticker:
        """
 Parses a combined midpoint + order book response into a unified CCXT Ticker object.
 @param ticker
 @param market
        """
        midpointData = self.safe_value(ticker, 'midpoint', {})
        bookData = self.safe_value(ticker, 'book', {})
        mid = self.safe_number(midpointData, 'mid')
        bids = self.safe_list(bookData, 'bids', [])
        asks = self.safe_list(bookData, 'asks', [])
        bestBid = self.safe_number(bids[0], 'price') if len(bids) else None
        bestAsk = self.safe_number(asks[0], 'price') if len(asks) else None
        symbol = self.safe_symbol(None, market)
        now = self.milliseconds()
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': now,
            'datetime': self.iso8601(now),
            'high': None,
            'low': None,
            'bid': bestBid,
            'bidVolume': self.safe_number(bids[0], 'size') if len(bids) else None,
            'ask': bestAsk,
            'askVolume': self.safe_number(asks[0], 'size') if len(asks) else None,
            'vwap': None,
            'open': None,
            'close': mid,
            'last': mid,
            'previousClose': None,
            'change': None,
            'percentage': None,
            'average': mid,
            'baseVolume': None,
            'quoteVolume': self.safe_number(market['info'], 'volume24h') if market else None,
            'info': ticker,
        }, market)

    async def fetch_order_book(self, outcome: str, limit: Int = None, params: dict = {}) -> OrderBook:
        """
 Fetches the CLOB order book for a single outcome token.
 @param outcome
 @param limit
 @param params

        https://docs.polymarket.com/api-reference/market-data/get-order-book

        """
        await self.load_markets()
        outcomeObj = self.outcome(outcome)
        tokenId = outcomeObj['id']
        request: dict = {
            'token_id': tokenId,
        }
        response = await self.clobPublicGetBook(self.extend(request, params))
        timestamp = self.milliseconds()
        return self.parse_order_book(response, outcome, timestamp, 'bids', 'asks', 'price', 'size')

    async def fetch_ohlcv(self, outcome: str, timeframe='1m', since: Int = None, limit: Int = None, params: dict = {}) -> List[list]:
        """
 Fetches price history ticks for a single outcome token and maps them to OHLCV format.
 @param outcome
 @param timeframe
 @param since
 @param limit
 @param params

        https://docs.polymarket.com/api-reference/markets/get-prices-history

        """
        await self.load_markets()
        outcomeObj = self.outcome(outcome)
        tokenId = outcomeObj['id']
        fidelity = self.safe_string(self.timeframes, timeframe, '1')
        request: dict = {
            'market': tokenId,
            'fidelity': fidelity,
        }
        if since is not None:
            request['startTs'] = self.parse_to_int(since / 1000)
        if limit is not None and since is not None:
            tf = self.parse_timeframe(timeframe)
            endS = (since / 1000) + limit * tf
            nowS = self.seconds()
            request['endTs'] = endS < endS if nowS else nowS
        response = await self.clobPublicGetPricesHistory(self.extend(request, params))
        history = self.safe_list(response, 'history', [])
        return self.parse_ohlcvs(history, outcomeObj, timeframe, since, limit)

    def parse_ohlcv(self, ohlcv: dict, market: Market = None) -> list:
        """
 Parses a single Polymarket prices-history tick `{t, p}` into a CCXT OHLCV tuple.
 @param ohlcv
 @param market
        """
        # Polymarket prices-history tick: {t: unix_seconds, p: price}
        ts = self.safe_integer(ohlcv, 't')
        price = self.safe_number(ohlcv, 'p')
        return [
            ts is not ts * 1000 if None else None,
            price,   # open  (raw tick — no OHLCV disaggregation available)
            price,   # high
            price,   # low
            price,   # close
            None,  # volume(not provided per-tick)
        ]

    async def fetch_trades(self, outcome: str, since: Int = None, limit: Int = None, params: dict = {}) -> List[Trade]:
        """
 Fetches public trade history for a single outcome token from the CLOB data endpoint.
 @param outcome
 @param since
 @param limit
 @param params

        https://docs.polymarket.com/api-reference/trade/get-trades

        """
        await self.load_markets()
        outcomeObj = self.outcome(outcome)
        tokenId = outcomeObj['id']
        request: dict = {'asset_id': tokenId}
        if limit is not None:
            request['limit'] = limit
        response = await self.clobPublicGetDataTrades(self.extend(request, params))
        trades = self.safe_list(response, 'data', [])
        return self.parse_trades(trades, outcomeObj, since, limit)

    def parse_trade(self, trade: dict, market: Market = None) -> Trade:
        """
 Parses a raw CLOB trade object into a unified CCXT Trade object.
 @param trade
 @param market
        """
        id = self.safe_string(trade, 'id')
        timestamp = self.safe_integer_product(trade, 'timestamp', 1000)
        price = self.safe_number(trade, 'price')
        amount = self.safe_number(trade, 'size')
        rawSide = self.safe_string_lower(trade, 'side')
        side = rawSide if (rawSide == 'buy' or rawSide == 'sell') else None
        symbol = self.safe_symbol(None, market)
        return self.safe_trade({
            'id': id,
            'info': trade,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': symbol,
            'order': self.safe_string(trade, 'orderId'),
            'type': None,
            'side': side,
            'takerOrMaker': None,
            'price': price,
            'amount': amount,
            'cost': None,
            'fee': None,
        }, market)

    async def fetch_balance(self, params: dict = {}) -> Balances:
        """
 Fetches the authenticated user's USDC portfolio value from the Data API.
 @param params

        https://docs.polymarket.com/api-reference/core/get-total-value-of-a-users-positions

        """
        request: dict = {
            'user': self.walletAddress,
        }
        response = await self.dataPrivateGetValue(self.extend(request, params))
        return self.parse_balance(response)

    def parse_balance(self, response: dict) -> Balances:
        """
 Parses a portfolio value response into a CCXT Balances object with a USDC entry.
 @param response
        """
        result: dict = {'info': response}
        total = self.safe_number(response, 'value', self.safe_number(response, 'total'))
        result['USDC'] = {
            'free': total,
            'used': 0,
            'total': total,
        }
        return result

    async def fetch_positions(self, outcomes: Strings = None, params: dict = {}) -> List[Position]:
        """
 Fetches open outcome token positions for the authenticated user from the Data API.
 @param outcomes
 @param params

        https://docs.polymarket.com/api-reference/core/get-current-positions-for-a-user

        """
        if self.walletAddress is None:
            raise ArgumentsRequired(self.id + ' walletAddress is required to fetchPositions')
        request = {
            'user': self.walletAddress,
        }
        response = await self.dataPrivateGetPositions(self.extend(request, params))
        positions = self.safe_list(response, 'data', [])
        return self.parse_positions(positions, outcomes)

    def parse_position(self, position: dict, market: Market = None) -> Position:
        """
 Parses a raw Data API position object into a unified CCXT Position object.
 @param position
 @param market
        """
        tokenId = self.safe_string(position, 'asset')
        marketData = self.safe_outcome(tokenId, market)
        size = self.safe_number(position, 'size')
        entryPrice = self.safe_number(position, 'avgPrice')
        curPrice = self.safe_number(position, 'currentPrice')
        # unrealizedPnl = (size is not None and entryPrice is not None and curPrice is not None)
        size * (curPrice - entryPrice)
        #     if  # else None
        return {
            'id': self.safe_string(position, 'id'),
            'symbol': marketData['symbol'],
            'timestamp': None,
            'datetime': None,
            'contracts': size,
            'contractSize': 1,
            'side': 'long',
            'notional': size * curPrice if (size is not None and curPrice is not None) else None,
            'leverage': 1,
            'unrealizedPnl': None,
            'realizedPnl': self.safe_number(position, 'realizedPnl'),
            'collateral': None,
            'entryPrice': entryPrice,
            'markPrice': curPrice,
            'liquidationPrice': None,
            'hedged': False,
            'maintenanceMargin': None,
            'maintenanceMarginPercentage': None,
            'initialMargin': None,
            'initialMarginPercentage': None,
            'marginRatio': None,
            'marginMode': 'cross',
            'marginType': 'cross',
            'percentage': None,
            'info': position,
        }

    async def fetch_open_orders(self, outcome: Str = None, since: Int = None, limit: Int = None, params: dict = {}) -> List[Order]:
        """
 Fetches open resting orders for the authenticated user, optionally filtered by outcome token.
 @param outcome
 @param since
 @param limit
 @param params

        https://docs.polymarket.com/api-reference/trade/get-user-orders

        """
        request: dict = {}
        outcomeObj: Any = None
        if outcome is not None:
            outcomeObj = self.outcome(outcome)
            request['asset_id'] = outcomeObj['id']
        response = await self.clobPrivateGetDataOrders(self.extend(request, params))
        orders = self.safe_list(response, 'data', [])
        return self.parse_orders(orders, outcomeObj, since, limit)

    async def fetch_order(self, id: Str, outcome: Str = None, params: dict = {}) -> Order:
        """
 Fetches a single order by ID from the CLOB private data endpoint.
 @param id
 @param symbol
 @param params

        https://docs.polymarket.com/api-reference/trade/get-single-order-by-id

        """
        request: dict = {'id': id}
        response = await self.clobPrivateGetDataOrderId(self.extend(request, params))
        return self.parse_order(response)

    def parse_order(self, order: dict, market: Market = None) -> Order:
        """
 Parses a raw CLOB order object into a unified CCXT Order object.
 @param order
 @param market
        """
        id = self.safe_string(order, 'id')
        tokenId = self.safe_string(order, 'asset_id')
        mkt = self.safe_outcome(tokenId, market)
        status = self.parse_order_status(self.safe_string(order, 'status'))
        side = self.safe_string_lower(order, 'side')
        price = self.safe_number(order, 'price')
        amount = self.safe_number(order, 'original_size')
        filled = self.safe_number(order, 'size_matched', 0)
        ts = self.safe_integer_product(order, 'created_at', 1000)
        return self.safe_order({
            'id': id,
            'clientOrderId': None,
            'info': order,
            'timestamp': ts,
            'datetime': self.iso8601(ts),
            'lastTradeTimestamp': None,
            'status': status,
            'symbol': mkt['symbol'],
            'type': self.safe_string_lower(order, 'type', 'limit'),
            'timeInForce': self.safe_string(order, 'time_in_force', 'GTC'),
            'postOnly': None,
            'side': side,
            'price': price,
            'stopPrice': None,
            'triggerPrice': None,
            'average': None,
            'amount': amount,
            'cost': None,
            'filled': filled,
            'remaining': None,
            'fee': None,
            'trades': [],
        }, mkt)

    def parse_order_status(self, status: Str) -> Str:
        """
 Maps a Polymarket order status string to the CCXT unified status vocabulary.
 @param status
        """
        statuses: dict = {
            'LIVE': 'open',
            'MATCHED': 'closed',
            'CANCELLED': 'canceled',
            'DELAYED': 'open',
        }
        return self.safe_string(statuses, status, status)

    async def create_order(self, outcome: str, type: Str, side: Str, amount: Num, price: Num = None, params: dict = {}) -> Order:
        """
 Places a limit or market order on the Polymarket CLOB for the given outcome token.
 @param outcome
 @param type
 @param side
 @param amount
 @param price
 @param params

        https://docs.polymarket.com/api-reference/trade/post-a-new-order

        """
        await self.load_markets()
        outcomeObj = self.outcome(outcome)
        tokenId = outcomeObj['id']
        sideStr = side.upper()
        typeStr = type.upper()
        request: dict = {
            'token_id': tokenId,
            'price': price,
            'size': amount,
            'side': sideStr,
            'type': typeStr,
        }
        response = await self.clobPrivatePostOrder(self.extend(request, params))
        return self.parse_order(response, outcomeObj)

    async def cancel_order(self, id: Str, outcome: Str = None, params: dict = {}) -> Order:
        """
 Cancels a single open order by ID on the Polymarket CLOB.
 @param id
 @param symbol
 @param params

        https://docs.polymarket.com/api-reference/trade/cancel-single-order

        """
        request: dict = {'order_id': id}
        response = await self.clobPrivateDeleteOrder(self.extend(request, params))
        return self.parse_order(response)

    async def cancel_all_orders(self, outcome: Str = None, params: dict = {}) -> List[Order]:
        """
 Cancels all open orders on the Polymarket CLOB, optionally scoped to one outcome token.
 @param outcome
 @param params

        https://docs.polymarket.com/api-reference/trade/cancel-all-orders

        """
        request: dict = {}
        if outcome is not None:
            outcomeObj = self.outcome(outcome)
            request['asset_id'] = outcomeObj['id']
        response = await self.clobPrivateDeleteOrders(self.extend(request, params))
        return self.parse_orders(response)

    async def fetch_events(self, queries: List[str] = [], params: dict = {}) -> Any:
        """
 Fetches events matching the given search terms via the Gamma public-search endpoint and
 merges them into self.events and self.markets; with no queries, fetches all active events.
 Returns the full self.events dict(all cached events, not just the newly fetched ones).
 @param queries
 @param params

        https://docs.polymarket.com/api-reference/search/search-markets-events-and-profiles

        """
        pageSize = self.safe_integer(params, 'limit', 50)
        rest = self.omit(params, ['limit'])
        # For each query: fetch page 1, then all remaining pages in parallel
        seen: dict = {}
        rawEvents: List[Any] = []
        for(q of queries) {
            baseRequest: dict = {'q': q, 'limit_per_type': pageSize, 'events_status': 'active'}
            firstRequest: dict = {'page': 1}
            first = await self.gammaPublicGetPublicSearch(self.extend(firstRequest, baseRequest, rest))
            firstEvents = self.safe_list(first, 'events', [])
            pagination = self.safe_value(first, 'pagination', {})
            totalResults = self.safe_integer(pagination, 'totalResults', len(firstEvents))
            totalPages = int(math.ceil(totalResults / pageSize))
            remainingPages: number[] = []
            for p in range(2, totalPages):
                remainingPages.append(p)
            restPromises3: Any[] = []
            for pi3 in range(0, len(remainingPages)):
                pageRequest: dict = {'page': remainingPages[pi3]}
                restPromises3.append(self.gammaPublicGetPublicSearch(self.extend(pageRequest, baseRequest, rest)))
            restResponses = await asyncio.gather(*restPromises3)
            allEvents: Any[] = (firstEvents).slice()
            for ri3 in range(0, len(restResponses)):
                pageEvents3 = self.safe_list(restResponses[ri3], 'events', [])
                for ei3 in range(0, len(pageEvents3)):
                    allEvents.append(pageEvents3[ei3])
            for(rawEvent of allEvents) {
                eventId = self.safe_string(rawEvent, 'id')
                if eventId and not seen[eventId]:
                    seen[eventId] = True
                    rawEvents.append(rawEvent)
        # Parse and merge into class-level caches
        if not self.events:
            self.events = {}
        if not self.markets:
            self.markets = {}
        for(rawEvent of rawEvents) {
            ccxtMarkets = self.parse_event_to_markets(rawEvent)
            for(m of ccxtMarkets) {
                self.markets[m['symbol']] = m
            parsedEvent = self.parse_event(rawEvent, ccxtMarkets)
            eventSlug = self.safe_string(rawEvent, 'slug')
            if eventSlug:
                eventKey = self.shorten_slugeventSlug
                self.events[eventKey] = parsedEvent
        return list(self.events.values())

    def parse_event(self, rawEvent: dict) -> dict:
        # {
        #     "id": "73113",
        #     "ticker": "ukraine-agrees-not-to-join-nato-before-2027",
        #     "slug": "ukraine-agrees-not-to-join-nato-before-2027",
        #     "title": "Ukraine agrees not to join NATO before 2027? ",
        #     "description": "This market will resolve to \\"Yes\\" if Ukraine publicly agrees not to join NATO by December 31, 2026, 11:59 PM ET. Otherwise, self market will resolve to “No”.\\n\\nAn official pledge by Ukraine not to join NATO will qualify for a “Yes” resolution whether unilateral announcement or part of an agreement with the Russian Federation.\\n\\nAny agreement or pledge made before the resolution date of self market will qualify, regardless of if/when the agreement goes into effect.\\n\\nAn agreement by Ukraine not to join NATO for any amount of time will count(e.g. If Ukraine not to join NATO for 10 years self will qualify).\\n\\nAn agreement by Ukraine not to join NATO precondition of a more comprehensive peace process or deal will qualify, even if the agreement is not finalized or part of a formalized peace deal. The September 8, 1995 “Agreed Basic Principles” between Bosnia and Yugoslavia which recognized the borders and sovereignty of Bosnia and Herzegovina, and was later formalized through the Dayton Peace Agreement is an example of a qualifying agreement. \\n\\nThe primary resolution source for self market will be an official announcement by the Ukraine, however an overwhelming consensus of credible reporting confirming a qualifying agreement has been reached will also count.",
        #     "resolutionSource": "",
        #     "startDate": "2025-11-05T17:00:57.200353Z",
        #     "creationDate": "2025-11-05T17:00:57.20035Z",
        #     "endDate": "2026-12-31T00:00:00Z",
        #     "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/ukraine-agrees-not-to-join-nato-before-july-vKEDpScXuAtt.jpg",
        #     "icon": "https://polymarket-upload.s3.us-east-2.amazonaws.com/ukraine-agrees-not-to-join-nato-before-july-vKEDpScXuAtt.jpg",
        #     "active": True,
        #     "closed": False,
        #     "archived": False,
        #     "new": False,
        #     "featured": False,
        #     "restricted": True,
        #     "liquidity": "22010.6659",
        #     "openInterest": "0",
        #     "createdAt": "2025-11-04T19:27:23.246129Z",
        #     "updatedAt": "2026-03-14T14:38:21.25643Z",
        #     "competitive": "0.9538344143456696",
        #     "enableOrderBook": True,
        #     "liquidityClob": "22010.6659",
        #     "commentCount": "0",
        #     "markets": [],
        #     "tags": [
        #         {
        #             "id": "101970",
        #             "label": "World",
        #             "slug": "world",
        #             "forceShow": False,
        #             "createdAt": "2025-03-19T23:36:08.498099Z",
        #             "updatedAt": "2026-03-09T22:25:02.420693Z",
        #             "requiresTranslation": False
        #         },
        #         {
        #             "id": "270",
        #             "label": "putin",
        #             "slug": "putin",
        #             "publishedAt": "2023-11-02 21:46:19.507+00",
        #             "createdAt": "2023-11-02T21:46:19.528Z",
        #             "updatedAt": "2026-03-09T22:29:44.08742Z",
        #             "requiresTranslation": False
        #         }
        #     ],
        #     "cyom": False,
        #     "showAllOutcomes": True,
        #     "showMarketImages": True,
        #     "enableNegRisk": False,
        #     "automaticallyActive": True,
        #     "seriesSlug": "ukraine-not-nato",
        #     "negRiskAugmented": False,
        #     "cumulativeMarkets": False,
        #     "pendingDeployment": False,
        #     "deploying": False,
        #     "requiresTranslation": False
        # }
        marketsList = self.parse_event_to_markets(rawEvent)
        slug = self.safe_string(rawEvent, 'slug')
        return self.extend({
            'id': self.safe_string(rawEvent, 'id'),
            'slug': slug,
            'symbol': self.shorten_slug(slug) if slug else None,
            'title': self.safe_string(rawEvent, 'title'),
            'markets': marketsList,
            'url': self.safe_string(rawEvent, 'url'),
            'image': self.safe_string(rawEvent, 'image_url'),
            'created': self.parse8601(self.safe_string(rawEvent, 'created_date_iso')),
            'createdDatetime': self.safe_string(rawEvent, 'created_date_iso'),
            'end': self.parse8601(self.safe_string(rawEvent, 'end_date_iso')),
            'endDatetime': self.safe_string(rawEvent, 'end_date_iso'),
            'category': self.safe_string(rawEvent, 'category'),
            'lastUpdatedAt': self.parse8601(self.safe_string(rawEvent, 'last_updated_date_iso')),
            'lastUpdatedAtDatetime': self.safe_string(rawEvent, 'last_updated_date_iso'),
            'resolutionSource': self.safe_string(rawEvent, 'resolution_source'),
            'resolved': self.safe_bool(rawEvent, 'resolved'),
            'info': rawEvent,
        })

    def parse_events(self, rawEvents: List[Any]) -> List[Any]:
        """
 Parses an array of raw Gamma event objects into unified CCXT event objects.
 @param rawEvents
        """
        result: List[Any] = []
        for(rawEvent of rawEvents) {
            result.append(self.parse_event(rawEvent))
        return result

    def sign(self, path: Str, api: Any = 'gamma', method='GET', params: dict = {}, headers: dict = None, body: dict = None):
        """
 Builds the request URL and attaches HMAC-SHA256 authentication headers for private endpoints.
 @param path
 @param api
 @param method
 @param params
 @param headers
 @param body
        """
        # api is either a string('gamma') or array(['gamma', 'public'])
        apiGroup: str = api if isinstance(api, str) else api[0]
        access: str = 'public' if isinstance(api, str) else api[1]
        baseUrls = self.urls['api']
        baseUrl = self.safe_string(baseUrls, apiGroup, baseUrls['gamma'])
        url = baseUrl + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_paramspath)
        querystring = self.urlencode(query)
        if method == 'GET' and querystring:
            url += '?' + querystring
        headers = self.extend({
            'Accept': 'application/json',
            'Content-Type': 'application/json',
        }, headers or {})
        if access == 'private':
            self.check_required_credentials()
            timestamp = str(self.seconds())
            signature = self.hmac(
                self.encode(timestamp + method + '/' + path),
                self.encode(self.secret),
                'sha256',
                'base64'
            )
            headers = self.extend(headers, {
                'POLY_ADDRESS': self.walletAddress,
                'POLY_API_KEY': self.apiKey,
                'POLY_PASSPHRASE': self.password,
                'POLY_SIGNATURE': signature,
                'POLY_TIMESTAMP': timestamp,
            })
            if method != 'GET' and querystring:
                body = query
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
